module.exports =   {
  '1': { 'code': '1', 'name': ["CENTRAL ALASKA", "CENTRAL DE ALASKA"] },
  '2': { 'code': '2', 'name': ["SOUTHERN ALASKA", "REGION AL SUR DE ALASKA"] },
  '3': { 'code': '3', 'name': ["BERING SEA", "MAR DE BERING"] },
  '4': { 'code': '4', 'name': ["KOMANDORSKY ISLANDS REGION", "REGION DE LAS ISLAS KOMANDORSKY"] },
  '5': { 'code': '5', 'name': ["NEAR ISLANDS, ALEUTIAN ISLANDS", "ISLAS NEAR, ISLAS ALEUTIANAS"] },
  '6': { 'code': '6', 'name': ["RAT ISLANDS, ALEUTIAN ISLANDS", "ISLAS RAT, ISLAS ALEUTIAN"] },
  '7': { 'code': '7', 'name': ["ANDREANOF ISLANDS, ALEUTIAN IS.", "ISLAS ANDREANOF, ISLAS ALEUTIAN"] },
  '8': { 'code': '8', 'name': ["PRIBILOF ISLANDS, ALASKA REGION", "ISLAS PRIBILOF, ALASKA"] },
  '9': { 'code': '9', 'name': ["FOX ISLANDS, ALEUTIAN ISLANDS", "ISLAS FOX, ALEUTIAN"] },
  '10': { 'code': '10', 'name': ["UNIMAK ISLAND REGION, ALASKA", "ISLAS UNIMAK, ALASKA"] },
  '11': { 'code': '11', 'name': ["BRISTOL BAY", "BAHIA DE BRISTOL"] },
  '12': { 'code': '12', 'name': ["ALASKA PENINSULA", "PENINSILA DE ALASKA"] },
  '13': { 'code': '13', 'name': ["KODIAK ISLAND REGION, ALASKA", "ISLAS KODIAK, ALASKA"] },
  '14': { 'code': '14', 'name': ["KENAI PENINSULA, ALASKA", "PENINSULA DE KENAI, ALASKA"] },
  '15': { 'code': '15', 'name': ["GULF OF ALASKA", "GOLFO DE ALASKA"] },
  '16': { 'code': '16', 'name': ["SOUTH OF ALEUTIAN ISLANDS", "REGION AL SUR DE LAS ISLAS ALEUTIAN"] },
  '17': { 'code': '17', 'name': ["SOUTH OF ALASKA", "REGION AL SUR DE ALASKA"] },
  '18': { 'code': '18', 'name': ["SOUTHERN YUKON TERRITORY, CANADA", "REGION SUR DE YUKON, CANADA"] },
  '19': { 'code': '19', 'name': ["SOUTHEASTERN ALASKA", "REGION SURESTE DE ALASKA"] },
  '20': { 'code': '20', 'name': ["OFF COAST OF SOUTHEASTERN ALASKA", "FRENTE A LA COSTA SURESTE DE ALASKA"] },
  '21': { 'code': '21', 'name': ["WEST OF VANCOUVER ISLAND", "REGION AL OESTE DE VANCOUVER"] },
  '22': { 'code': '22', 'name': ["QUEEN CHARLOTTE ISLANDS REGION", "ISLA REINA CHARLOTTE"] },
  '23': { 'code': '23', 'name': ["BRITISH COLUMBIA, CANADA", "COLUMBIA BRITANICA, CANADA"] },
  '24': { 'code': '24', 'name': ["ALBERTA, CANADA", "ALBERTA, CANADA"] },
  '25': { 'code': '25', 'name': ["VANCOUVER ISLAND, CANADA REGION", "ISLA DE VANCOUVER, CANADA"] },
  '26': { 'code': '26', 'name': ["OFF COAST OF WASHINGTON", "FRENTE A LA COSTA DE WASHINGTON"] },
  '27': { 'code': '27', 'name': ["NEAR COAST OF WASHINGTON", "CERCA A LA COSTA DE WASHINGTON"] },
  '28': { 'code': '28', 'name': ["WASHINGTON-OREGON BORDER REGION", "REGION FRONTERIZA WASHINGTON-OREGON"] },
  '29': { 'code': '29', 'name': ["WASHINGTON", "WASHINGTON"] },
  '30': { 'code': '30', 'name': ["OFF COAST OF OREGON", "FRENTE A LA COSTA DE OREGON"] },
  '31': { 'code': '31', 'name': ["NEAR COAST OF OREGON", "CERCA DE LA COSTA DE OREGON"] },
  '32': { 'code': '32', 'name': ["OREGON", "OREGON"] },
  '33': { 'code': '33', 'name': ["WESTERN IDAHO", "REGION OESTE DE IDAHO"] },
  '34': { 'code': '34', 'name': ["OFF COAST OF NORTHERN CALIFORNIA", "FRENTE A LA COSTA NORTE DE CALIFORNIA"] },
  '35': { 'code': '35', 'name': ["NEAR COAST OF NORTHERN CALIF.", "CERCA A LA COSTA NORTE DE CALIFORNIA"] },
  '36': { 'code': '36', 'name': ["NORTHERN CALIFORNIA", "REGION NORTE DE CALIFORNIA"] },
  '37': { 'code': '37', 'name': ["NEVADA", "NEVADA"] },
  '38': { 'code': '38', 'name': ["OFF COAST OF CALIFORNIA", "FRENTE A LA COSTA DE CALIFORNIA"] },
  '39': { 'code': '39', 'name': ["CENTRAL CALIFORNIA", "REGION CENTRAL DE CALIFORNIA"] },
  '40': { 'code': '40', 'name': ["CALIFORNIA-NEVADA BORDER REGION", "REGION FRONTERIZA CALIFORNIA-NEVADA"] },
  '41': { 'code': '41', 'name': ["SOUTHERN NEVADA", "REGION SUR DE NEVADA"] },
  '42': { 'code': '42', 'name': ["WESTERN ARIZONA", "REGION OESTE DE ARIZONA"] },
  '43': { 'code': '43', 'name': ["SOUTHERN CALIFORNIA", "REGION SUR DE CALIFORNIA"] },
  '44': { 'code': '44', 'name': ["CALIFORNIA-ARIZONA BORDER REGION", "REGION FRONTERIZA CALIFORNIA-ARIZONA"] },
  '45': { 'code': '45', 'name': ["CALIF.-BAJA CALIF. BORDER REGION", "REGION FRONTERIZA CALIF. BAJA CALIF."] },
  '46': { 'code': '46', 'name': ["W. ARIZONA-SONORA BORDER REGION", "REGION FRONTERIZA W. ARIZONA-SONORA"] },
  '47': { 'code': '47', 'name': ["OFF W. COAST OF BAJA CALIFORNIA", "FRENTE A LA COSTA DE BAJA CALIFORNIA"] },
  '48': { 'code': '48', 'name': ["BAJA CALIFORNIA, MEXICO", "BAJA CALIFORNIA, MEXICO"] },
  '49': { 'code': '49', 'name': ["GULF OF CALIFORNIA", "GOLFO DE CALIFORNIA"] },
  '50': { 'code': '50', 'name': ["SONORA, MEXICO", "SONORA, MEXICO"] },
  '51': { 'code': '51', 'name': ["OFF COAST OF CENTRAL MEXICO", "FRENTE LA COSTA CENTRAL DE MEXICO"] },
  '52': { 'code': '52', 'name': ["NEAR COAST OF CENTRAL MEXICO", "CERCA A LA COSTA CENTRAL DE MEXICO"] },
  '53': { 'code': '53', 'name': ["REVILLA GIGEDO ISLANDS REGION", "ISLAS DE REVILLA GIGEDO"] },
  '54': { 'code': '54', 'name': ["OFF COAST OF JALISCO, MEXICO", "FRENTE A LA COSTA DE JALISCO, MEXICO"] },
  '55': { 'code': '55', 'name': ["NEAR COAST OF JALISCO, MEXICO", "CERCA A LA COSTA DE JALISCO, MEXICO"] },
  '56': { 'code': '56', 'name': ["NEAR COAST OF MICHOACAN, MEXICO", "CERCA A LA COSTA DE MICHOACAN, MEXICO"] },
  '57': { 'code': '57', 'name': ["MICHOACAN, MEXICO", "MICHOACAN, MEXICO"] },
  '58': { 'code': '58', 'name': ["NEAR COAST OF GUERRERO, MEXICO", "CERCA A LA COSTA DE GUERRERO, MEXICO"] },
  '59': { 'code': '59', 'name': ["GUERRERO, MEXICO", "GUERRERO, MEXICO"] },
  '60': { 'code': '60', 'name': ["OAXACA, MEXICO", "OAXACA, MEXICO"] },
  '61': { 'code': '61', 'name': ["CHIAPAS, MEXICO", "CHIAPAS, MEXICO"] },
  '62': { 'code': '62', 'name': ["MEXICO-GUATEMALA BORDER REGION", "REGION FRONTERIZA MEXICO-GUATEMALA"] },
  '63': { 'code': '63', 'name': ["OFF COAST OF MEXICO", "FRENTE A LA COSTA DE MEXICO"] },
  '64': { 'code': '64', 'name': ["OFF COAST OF MICHOACAN, MEXICO", "FRENTE A LA COSTA DE MICHOACAN, MEXICO"] },
  '65': { 'code': '65', 'name': ["OFF COAST OF GUERRERO, MEXICO", "FRENTE A LA COSTA DE GUERRERO, MEXICO"] },
  '66': { 'code': '66', 'name': ["NEAR COAST OF OAXACA, MEXICO", "CERCA A LA COSTA DE OAXACA, MEXICO"] },
  '67': { 'code': '67', 'name': ["OFF COAST OF OAXACA, MEXICO", "FRENTE A LA COSTA DE OAXACA, MEXICO"] },
  '68': { 'code': '68', 'name': ["OFF COAST OF CHIAPAS, MEXICO", "FRENTE A LA COSTA DE CHIAPAS, MEXICO"] },
  '69': { 'code': '69', 'name': ["NEAR COAST OF CHIAPAS, MEXICO", "CERCA A LA COSTA DE CHIAPAS, MEXICO"] },
  '70': { 'code': '70', 'name': ["GUATEMALA", "GUATEMALA"] },
  '71': { 'code': '71', 'name': ["NEAR COAST OF GUATEMALA", "CERCA A LA COSTA DE GUATEMALA"] },
  '72': { 'code': '72', 'name': ["HONDURAS", "HONDURAS"] },
  '73': { 'code': '73', 'name': ["EL SALVADOR", "EL SALVADOR"] },
  '74': { 'code': '74', 'name': ["NEAR COAST OF NICARAGUA", "CERCA A LA COSTA DE NICARAGUA"] },
  '75': { 'code': '75', 'name': ["NICARAGUA", "NICARAGUA"] },
  '76': { 'code': '76', 'name': ["OFF COAST OF CENTRAL AMERICA", "FRENTE A LA COSTA DE AMERICA CENTRAL"] },
  '77': { 'code': '77', 'name': ["OFF COAST OF COSTA RICA", "FRENTE A LA COSTA DE COSTA RICA"] },
  '78': { 'code': '78', 'name': ["COSTA RICA", "COSTA RICA"] },
  '79': { 'code': '79', 'name': ["NORTH OF PANAMA", "REGION NORTE DE PANAMA"] },
  '80': { 'code': '80', 'name': ["PANAMA-COSTA RICA BORDER REGION", "REGION FRONTERIZA PANAMA-COSTA RICA"] },
  '81': { 'code': '81', 'name': ["PANAMA", "PANAMA"] },
  '82': { 'code': '82', 'name': ["PANAMA-COLOMBIA BORDER REGION", "REGION FRONTERIZA PANAMA-COLOMBIA"] },
  '83': { 'code': '83', 'name': ["SOUTH OF PANAMA", "REGION SUR DE PANAMA"] },
  '84': { 'code': '84', 'name': ["YUCATAN PENINSULA, MEXICO", "PENINSULA DE YUCATAN, MEXICO"] },
  '85': { 'code': '85', 'name': ["CUBA REGION", "CUBA"] },
  '86': { 'code': '86', 'name': ["JAMAICA REGION", "JAMAICA"] },
  '87': { 'code': '87', 'name': ["HAITI REGION", "HAITI"] },
  '88': { 'code': '88', 'name': ["DOMINICAN REPUBLIC REGION", "REPUBLICA DOMINICANA"] },
  '89': { 'code': '89', 'name': ["MONA PASSAGE", "PASAJE DE LA MONA"] },
  '90': { 'code': '90', 'name': ["PUERTO RICO REGION", "PUERTO RICO"] },
  '91': { 'code': '91', 'name': ["VIRGIN ISLANDS", "ISLAS VIRGENES"] },
  '92': { 'code': '92', 'name': ["LEEWARD ISLANDS", "ISLAS DE BARLOVENTO"] },
  '93': { 'code': '93', 'name': ["BELIZE", "BELIZE"] },
  '94': { 'code': '94', 'name': ["CARIBBEAN SEA", "MAR CARIBE"] },
  '95': { 'code': '95', 'name': ["WINDWARD ISLANDS", "ISLAS DE SOTAVENTO"] },
  '96': { 'code': '96', 'name': ["NEAR NORTH COAST OF COLOMBIA", "CERCA DE LA COSTA CARIBE DE COLOMBIA"] },
  '97': { 'code': '97', 'name': ["NEAR COAST OF VENEZUELA", "CERCA DE LA COSTA DE VENEZUELA"] },
  '98': { 'code': '98', 'name': ["TRINIDAD", "TRINIDAD"] },
  '99': { 'code': '99', 'name': ["NORTHERN COLOMBIA", "REGION NORTE DE COLOMBIA"] },
  '100': { 'code': '100', 'name': ["LAKE MARACAIBO, VENEZUELA", "LAGO DE MARACAIBO, VENEZUELA"] },
  '101': { 'code': '101', 'name': ["VENEZUELA", "VENEZUELA"] },
  '102': { 'code': '102', 'name': ["NEAR WEST COAST OF COLOMBIA", "CERCA DE LA COSTA PACIFICA DE COLOMBIA"] },
  '103': { 'code': '103', 'name': ["COLOMBIA", "COLOMBIA"] },
  '104': { 'code': '104', 'name': ["OFF COAST OF ECUADOR", "FRENTE A LA COSTA DE ECUADOR"] },
  '105': { 'code': '105', 'name': ["NEAR COAST OF ECUADOR", "CERCA DE LA COSTA DE ECUADOR"] },
  '106': { 'code': '106', 'name': ["COLOMBIA-ECUADOR BORDER REGION", "REGION FRONTERIZA COLOMBIA-ECUADOR"] },
  '107': { 'code': '107', 'name': ["ECUADOR", "ECUADOR"] },
  '108': { 'code': '108', 'name': ["OFF COAST OF NORTHERN PERU", "FRENTE A LA COSTA DE LA ZONA NORTE DE PERU"] },
  '109': { 'code': '109', 'name': ["NEAR COAST OF NORTHERN PERU", "CERCA A LA COSTA DE LA ZONA NORTE DE PERU"] },
  '110': { 'code': '110', 'name': ["PERU-ECUADOR BORDER REGION", "REGION FRONTERIZA PERU-ECUADOR"] },
  '111': { 'code': '111', 'name': ["NORTHERN PERU", "REGION NORTE DE PERU"] },
  '112': { 'code': '112', 'name': ["PERU-BRAZIL BORDER REGION", "REGION FRONTERIZA PERU-BRAZIL"] },
  '113': { 'code': '113', 'name': ["WESTERN BRAZIL", "ZONA OESTE DE BRASIL"] },
  '114': { 'code': '114', 'name': ["OFF COAST OF PERU", "FRENTE A LA COSTA DE PERU"] },
  '115': { 'code': '115', 'name': ["NEAR COAST OF PERU", "CERCA A LA COSTA DE PERU"] },
  '116': { 'code': '116', 'name': ["CENTRAL PERU", "REGION CENTRAL DE PERU"] },
  '117': { 'code': '117', 'name': ["SOUTHERN PERU", "REGION SUR DE PERU"] },
  '118': { 'code': '118', 'name': ["PERU-BOLIVIA BORDER REGION", "REGION FRONTERIZA PERU-BOLIVIA"] },
  '119': { 'code': '119', 'name': ["NORTHERN BOLIVIA", "REGION NORTE DE BOLIVIA"] },
  '120': { 'code': '120', 'name': ["CENTRAL BOLIVIA", "REGION CENTRAL DE BOLIVIA"] },
  '121': { 'code': '121', 'name': ["OFF COAST OF NORTHERN CHILE", "FRENTE A LA COSTA DE LA ZONA NORTE DE CHILE"] },
  '122': { 'code': '122', 'name': ["NEAR COAST OF NORTHERN CHILE", "CERCA DE LA COSTA DE LA ZONA NORTE DE CHILE"] },
  '123': { 'code': '123', 'name': ["NORTHERN CHILE", "REGION NORTE DE CHILE"] },
  '124': { 'code': '124', 'name': ["CHILE-BOLIVIA BORDER REGION", "REGION FRONTERIZA CHILE-BOLIVIA"] },
  '125': { 'code': '125', 'name': ["SOUTHERN BOLIVIA", "REGION SUR DE BOLIVIA"] },
  '126': { 'code': '126', 'name': ["PARAGUAY", "PARAGUAY"] },
  '127': { 'code': '127', 'name': ["CHILE-ARGENTINA BORDER REGION", "REGION FRONTERIZA CHILE-ARGENTINA"] },
  '128': { 'code': '128', 'name': ["JUJUY PROVINCE, ARGENTINA", "PROVINCIA DE JUJUY, ARGENTINA"] },
  '129': { 'code': '129', 'name': ["SALTA PROVINCE, ARGENTINA", "PROVINCIA DE SALTA, ARGENTINA"] },
  '130': { 'code': '130', 'name': ["CATAMARCA PROVINCE, ARGENTINA", "PROVINCIA DE CATAMARCA, ARGENTINA"] },
  '131': { 'code': '131', 'name': ["TUCUMAN PROVINCE, ARGENTINA", "PROVINCIA DE TUCUMAN, ARGENTINA"] },
  '132': { 'code': '132', 'name': ["SANTIAGO DEL ESTERO PROV., ARG.", "PROVINCIA DE SANTIAGO DEL ESTERO, ARGENTINA"] },
  '133': { 'code': '133', 'name': ["NORTHEASTERN ARGENTINA", "REGION NORESTE DE ARGENTINA"] },
  '134': { 'code': '134', 'name': ["OFF COAST OF CENTRAL CHILE", "FRENTE A LA COSTA CENTRAL DE CHILE"] },
  '135': { 'code': '135', 'name': ["NEAR COAST OF CENTRAL CHILE", "CERCA DE LA COSTA CENTRAL DE CHILE"] },
  '136': { 'code': '136', 'name': ["CENTRAL CHILE", "REGION CENTRAL DE CHILE"] },
  '137': { 'code': '137', 'name': ["SAN JUAN PROVINCE, ARGENTINA", "PROVINCIA DE SAN JUAN, ARGENTINA"] },
  '138': { 'code': '138', 'name': ["LA RIOJA PROVINCE, ARGENTINA", "PROVINCIA LA RIOJA, ARGENTINA"] },
  '139': { 'code': '139', 'name': ["MENDOZA PROVINCE, ARGENTINA", "PROVINCIA MENDOZA, ARGENTINA"] },
  '140': { 'code': '140', 'name': ["SAN LUIS PROVINCE, ARGENTINA", "PROVINCIA SAN LUIS, ARGENTINA"] },
  '141': { 'code': '141', 'name': ["CORDOBA PROVINCE, ARGENTINA", "PROVINCIA CORDOVA, ARGENTINA"] },
  '142': { 'code': '142', 'name': ["URUGUAY", "URUGUAY"] },
  '143': { 'code': '143', 'name': ["OFF COAST OF SOUTHERN CHILE", "FRENTE A LA COSTA DE LA ZONA SUR DE CHILE"] },
  '144': { 'code': '144', 'name': ["SOUTHERN CHILE", "REGION SUR DE CHILE"] },
  '145': { 'code': '145', 'name': ["S. CHILE-ARGENTINA BORDER REGION", "REGION FRONTERIZA SUR CHILE-ARGENTINA"] },
  '146': { 'code': '146', 'name': ["SOUTHERN ARGENTINA", "REGION SUR DE ARGENTINA"] },
  '147': { 'code': '147', 'name': ["TIERRA DEL FUEGO", "TIERRA DEL FUEGO"] },
  '148': { 'code': '148', 'name': ["FALKLAND ISLANDS REGION", "REGION ISLAS FALKLAND"] },
  '149': { 'code': '149', 'name': ["DRAKE PASSAGE", "PASAJE DE DRAKE"] },
  '150': { 'code': '150', 'name': ["SCOTIA SEA", "MAR DE ESCOCIA"] },
  '151': { 'code': '151', 'name': ["SOUTH GEORGIA ISLAND REGION", "REGION SUR DE LA ISLA GEORGIA"] },
  '152': { 'code': '152', 'name': ["SOUTH GEORGIA RISE", "LEVANTAMIENTO DEL SUR DE GEORGIA"] },
  '153': { 'code': '153', 'name': ["SOUTH SANDWICH ISLANDS REGION", "REGION SUR DE LAS ISLAS SANDWICH"] },
  '154': { 'code': '154', 'name': ["SOUTH SHETLAND ISLANDS", "SUR DE LAS ISLAS SHETLAND"] },
  '155': { 'code': '155', 'name': ["ANTARCTIC PENINSULA", "PENINSULA ANTARTICA"] },
  '156': { 'code': '156', 'name': ["SOUTHWESTERN ATLANTIC OCEAN", "REGION SUROESTE DEL OCEANO ATLANTICO"] },
  '157': { 'code': '157', 'name': ["WEDDELL SEA", "MAR WEDDELL"] },
  '158': { 'code': '158', 'name': ["OFF W. COAST OF N. ISLAND, N.Z.", "FRENTE A LA COSTA OESTE DE NEW ISLAND, N.Z."] },
  '159': { 'code': '159', 'name': ["NORTH ISLAND, NEW ZEALAND", "ISLA NORTE, NUEVA ZELANDA"] },
  '160': { 'code': '160', 'name': ["OFF E. COAST OF N. ISLAND, N.Z.", "FUERA DE LA COSTA ESTE DE ISLA N., N.Z."] },
  '161': { 'code': '161', 'name': ["OFF W. COAST OF S. ISLAND, N.Z.", "FUERA DE LA COSTA OESTE DE LA ISLA SUR, N.Z."] },
  '162': { 'code': '162', 'name': ["SOUTH ISLAND, NEW ZEALAND", "ISLAS SUR, NUEVA ZELANDA"] },
  '163': { 'code': '163', 'name': ["COOK STRAIT, NEW ZEALAND", "ESTRECHO DE COOK, NUEVA ZELANDA"] },
  '164': { 'code': '164', 'name': ["OFF E. COAST OF S. ISLAND, N.Z.", "FUERA DE LA COSTA ESTE DE LAS ISLAS SUR, N.Z."] },
  '165': { 'code': '165', 'name': ["NORTH OF MACQUARIE ISLAND", "NORTE DE LA ISLA MACQUARIE"] },
  '166': { 'code': '166', 'name': ["AUCKLAND ISLANDS, N.Z.  REGION", "REGION DE LAS ISLAS AUCKLAND, NUEVA ZELANDA"] },
  '167': { 'code': '167', 'name': ["MACQUARIE ISLAND REGION", "REGION DE LA ISLA MACQUARIE"] },
  '168': { 'code': '168', 'name': ["SOUTH OF NEW ZEALAND", "SUR DE NUEVA ZELANDA"] },
  '169': { 'code': '169', 'name': ["SAMOA ISLANDS REGION", "REGION ISLAS SAMOA"] },
  '170': { 'code': '170', 'name': ["SAMOA ISLANDS", "ISLAS SAMOA"] },
  '171': { 'code': '171', 'name': ["SOUTH OF FIJI ISLANDS", "SUR DE LAS ISLAS FIJI"] },
  '172': { 'code': '172', 'name': ["WEST OF TONGA ISLANDS", "OESTE DE LAS ISLAS DE TONGA"] },
  '173': { 'code': '173', 'name': ["TONGA ISLANDS", "ISLAS DE TONGA"] },
  '174': { 'code': '174', 'name': ["TONGA ISLANDS REGION", "REGION ISLAS DE TONGA"] },
  '175': { 'code': '175', 'name': ["SOUTH OF TONGA ISLANDS", "SUR DE LAS ISLAS DE TONGA"] },
  '176': { 'code': '176', 'name': ["NORTH OF NEW ZEALAND", "NORTE DE NUEVA ZELANDA"] },
  '177': { 'code': '177', 'name': ["KERMADEC ISLANDS REGION", "REGION DE LAS ISLAS KERMADEC"] },
  '178': { 'code': '178', 'name': ["KERMADEC ISLANDS, NEW ZEALAND", "ISLAS KERMADEC, NUEVA ZELANDA"] },
  '179': { 'code': '179', 'name': ["SOUTH OF KERMADEC ISLANDS", "SUR DE LAS ISLAS KERMADEC"] },
  '180': { 'code': '180', 'name': ["NORTH OF FIJI ISLANDS", "NORTE DE LAS ISLAS FIJI"] },
  '181': { 'code': '181', 'name': ["FIJI ISLANDS REGION", "REGION ISLAS FIJI"] },
  '182': { 'code': '182', 'name': ["FIJI ISLANDS", "ISLAS FIJI"] },
  '183': { 'code': '183', 'name': ["SANTA CRUZ ISLANDS REGION", "REGION ISLAS SANTA CRUZ"] },
  '184': { 'code': '184', 'name': ["SANTA CRUZ ISLANDS", "ISLAS SANTA CRUZ"] },
  '185': { 'code': '185', 'name': ["VANUATU ISLANDS REGION", "REGION ISLAS VANATU"] },
  '186': { 'code': '186', 'name': ["VANUATU ISLANDS", "ISLAS VANATU"] },
  '187': { 'code': '187', 'name': ["NEW CALEDONIA", "NUEVA CALEDONIA"] },
  '188': { 'code': '188', 'name': ["LOYALTY ISLANDS", "ISLAS LOYALTY"] },
  '189': { 'code': '189', 'name': ["SOUTHEAST OF LOYALTY ISLANDS", "SURESTE DE LAS ISLAS LOYALTY"] },
  '190': { 'code': '190', 'name': ["NEW IRELAND REGION, P.N.G.", "REGION NUEVA IRLANDA, P.N.G."] },
  '191': { 'code': '191', 'name': ["NORTH OF SOLOMON ISLANDS", "NORTE DE LAS ISLAS SOLOMON"] },
  '192': { 'code': '192', 'name': ["NEW BRITAIN REGION, P.N.G.", "REGION NUEVA BRETANA, P.N.G."] },
  '193': { 'code': '193', 'name': ["SOLOMON ISLANDS", "ISLAS SALOMON"] },
  '194': { 'code': '194', 'name': ["D ENTRECASTEAUX ISLANDS REGION", "REGION ISLAS D ENTRECASTEAUX"] },
  '195': { 'code': '195', 'name': ["SOUTH OF SOLOMON ISLANDS", "SUR DE LAS ISLAS SALOMON"] },
  '196': { 'code': '196', 'name': ["IRIAN JAYA REGION, INDONESIA", "REGION IRIAN JAYA, INDONESIA"] },
  '197': { 'code': '197', 'name': ["NEAR NORTH COAST OF IRIAN JAYA", "CERCA DE LA COSTA DE IRIAN JAYA"] },
  '198': { 'code': '198', 'name': ["NINIGO ISLANDS REGION, P.N.G.", "REGION ISLAS NINIGO,P.N.G."] },
  '199': { 'code': '199', 'name': ["ADMIRALTY ISLANDS REGION, P.N.G.", "REGION ISLAS ADMIRALTY, P.N.G."] },
  '200': { 'code': '200', 'name': ["NEAR N COAST OF NEW GUINEA, PNG.", "CERCA DE LA COSTA NORTE DE NUEVA GUINEA, P.N.G."] },
  '201': { 'code': '201', 'name': ["IRIAN JAYA, INDONESIA", "IRIAN JAYA, INDONESIA"] },
  '202': { 'code': '202', 'name': ["NEW GUINEA, PAPUA NEW GUINEA", "NUEVA GUINEA, PAPUA NUEVA GUINEA"] },
  '203': { 'code': '203', 'name': ["BISMARCK SEA", "MAR DE BISMARCK"] },
  '204': { 'code': '204', 'name': ["ARU ISLANDS REGION, INDONESIA", "REGION SILAS ARU, INDONESIA"] },
  '205': { 'code': '205', 'name': ["NEAR SOUTH COAST OF IRIAN JAYA", "CERCA DE LA COSTA SUR DE IRIAN JAYA"] },
  '206': { 'code': '206', 'name': ["NEAR S COAST OF NEW GUINEA, PNG.", "CERCA DE LA COSTA SUR DE NUEVA GUINEA, P.N.G."] },
  '207': { 'code': '207', 'name': ["EASTERN NEW GUINEA REG., P.N.G.", "REGION ESTE NUEVA GUINEA, P.N.G."] },
  '208': { 'code': '208', 'name': ["ARAFURA SEA", "MAR ARAFURA"] },
  '209': { 'code': '209', 'name': ["W. CAROLINE ISLANDS, MICRONESIA", "OESTE ISLAS CAROLINE, MICRONESIA"] },
  '210': { 'code': '210', 'name': ["SOUTH OF MARIANA ISLANDS", "SUR DE LAS ISLAS MARIANA"] },
  '211': { 'code': '211', 'name': ["SOUTHEAST OF HONSHU, JAPAN", "SURESTE DE HONSHU, JAPON"] },
  '212': { 'code': '212', 'name': ["BONIN ISLANDS, JAPAN REGION", "ISLAS BONIN, REGION DE JAPON"] },
  '213': { 'code': '213', 'name': ["VOLCANO ISLANDS, JAPAN REGION", "ISLAS VOLCAN, REGION DE JAPON"] },
  '214': { 'code': '214', 'name': ["WEST OF MARIANA ISLANDS", "OESTE DE LAS ISLAS MARIANA"] },
  '215': { 'code': '215', 'name': ["MARIANA ISLANDS REGION", "REGION ISLAS MARIANA"] },
  '216': { 'code': '216', 'name': ["MARIANA ISLANDS", "ISLAS MARIANA"] },
  '217': { 'code': '217', 'name': ["KAMCHATKA PENINSULA, RUSSIA", "PENINSULA KAMCHATKA, RUSIA"] },
  '218': { 'code': '218', 'name': ["NEAR EAST COAST OF KAMCHATKA", "CERCA DE LA COSTA DE KAMCHATKA"] },
  '219': { 'code': '219', 'name': ["OFF EAST COAST OF KAMCHATKA", "FUERA DE LA COSTA ESTE DE KAMCHATKA"] },
  '220': { 'code': '220', 'name': ["NORTHWEST OF KURIL ISLANDS", "NOROESTE DE LAS ISLAS KURIL"] },
  '221': { 'code': '221', 'name': ["KURIL ISLANDS", "ISLAS KURIL"] },
  '222': { 'code': '222', 'name': ["EAST OF KURIL ISLANDS", "ESTE DE LAS ISLAS KURIL"] },
  '223': { 'code': '223', 'name': ["EASTERN SEA OF JAPAN", "REGION ESTE DEL MAR DE JAPON"] },
  '224': { 'code': '224', 'name': ["HOKKAIDO, JAPAN  REGION", "HOKKAIDO, REGION DE JAPON"] },
  '225': { 'code': '225', 'name': ["OFF COAST OF HOKKAIDO, JAPAN", "FUERA DE LA COSTA DE HOKKAIDO, JAPON"] },
  '226': { 'code': '226', 'name': ["NEAR WEST COAST OF HONSHU, JAPAN", "CERCA DE LA COSTA OESTE DE HONSHU, JAPON"] },
  '227': { 'code': '227', 'name': ["EASTERN HONSHU, JAPAN", "REGION ESTE DE HONSHU,JAPON"] },
  '228': { 'code': '228', 'name': ["NEAR EAST COAST OF HONSHU, JAPAN", "CERCA DE LA COSTA ESTE DE HONSHU, JAPON"] },
  '229': { 'code': '229', 'name': ["OFF EAST COAST OF HONSHU, JAPAN", "FUERA DE LA COSTA ESTE DE HONSHU, JAPON"] },
  '230': { 'code': '230', 'name': ["NEAR S. COAST OF HONSHU, JAPAN", "CERCA DE LA COSTA SUR DE HONSHU, JAPON"] },
  '231': { 'code': '231', 'name': ["SOUTH KOREA", "SUR DE KOREA"] },
  '232': { 'code': '232', 'name': ["WESTERN HONSHU, JAPAN", "REGION OESTE DE HONSHU, JAPON"] },
  '233': { 'code': '233', 'name': ["NEAR S. COAST OF WESTERN HONSHU", "CERCA DE LA COSTA SUR DE LA REGION OESTE DE HONSHU"] },
  '234': { 'code': '234', 'name': ["NORTHWEST OF RYUKYU ISLANDS", "NOROESTE DE ISLAS RIUKYU"] },
  '235': { 'code': '235', 'name': ["KYUSHU, JAPAN", "KYUSHU, JAPON"] },
  '236': { 'code': '236', 'name': ["SHIKOKU, JAPAN", "SHIKOKU, JAPON"] },
  '237': { 'code': '237', 'name': ["SOUTHEAST OF SHIKOKU, JAPAN", "SURESTE DE SHIKOKU, JAPON"] },
  '238': { 'code': '238', 'name': ["RYUKYU ISLANDS, JAPAN", "ISLAS RIUKYU. JAPON"] },
  '239': { 'code': '239', 'name': ["SOUTHEAST OF RYUKYU ISLANDS", "SURESTE DE LAS ISLAS RIUKYU"] },
  '240': { 'code': '240', 'name': ["WEST OF BONIN ISLANDS", "OESTE DE LAS ISLAS BONIN"] },
  '241': { 'code': '241', 'name': ["PHILIPPINE SEA", "MAR DE FILIPINAS"] },
  '242': { 'code': '242', 'name': ["NEAR COAST OF SOUTHEASTERN CHINA", "CERCA DE LA COSTA DE LA REGION ESTE DE CHINA"] },
  '243': { 'code': '243', 'name': ["TAIWAN REGION", "REGION DE TAIWAN"] },
  '244': { 'code': '244', 'name': ["TAIWAN", "TAIWAN"] },
  '245': { 'code': '245', 'name': ["NORTHEAST OF TAIWAN", "NORESTE DE TAIWAN"] },
  '246': { 'code': '246', 'name': ["SOUTHWESTERN RYUKYU ISL., JAPAN", "SUROESTE DE LAS ISLAS RIUKYU, JAPON"] },
  '247': { 'code': '247', 'name': ["SOUTHEAST OF TAIWAN", "SURESTE DE TAIWAN"] },
  '248': { 'code': '248', 'name': ["PHILIPPINE ISLANDS REGION", "REGION ISLAS FILIPINAS"] },
  '249': { 'code': '249', 'name': ["LUZON, PHILIPPINES", "LUZON, FILIPINAS"] },
  '250': { 'code': '250', 'name': ["MINDORO, PHILIPPINES", "MINDORO, FILIPINAS"] },
  '251': { 'code': '251', 'name': ["SAMAR, PHILIPPINES", "SAMAR, FILIPINAS"] },
  '252': { 'code': '252', 'name': ["PALAWAN, PHILIPPINES", "PALAWAN, FILIPINAS"] },
  '253': { 'code': '253', 'name': ["SULU SEA", "MAR SULU"] },
  '254': { 'code': '254', 'name': ["PANAY, PHILIPPINES", "PANAY, FILIPINAS"] },
  '255': { 'code': '255', 'name': ["CEBU, PHILIPPINES", "CEBU, FILIPINAS"] },
  '256': { 'code': '256', 'name': ["LEYTE, PHILIPPINES", "LEYTE, FILIPINAS"] },
  '257': { 'code': '257', 'name': ["NEGROS, PHILIPPINES", "NEGROS, FILIPINAS"] },
  '258': { 'code': '258', 'name': ["SULU ARCHIPELAGO, PHILIPPINES", "ARCHIPIELAGO SULU, FILIPINAS"] },
  '259': { 'code': '259', 'name': ["MINDANAO, PHILIPPINES", "MINDANAO, FILIPINAS"] },
  '260': { 'code': '260', 'name': ["EAST OF PHILIPPINE ISLANDS", "ESTE DE LAS ISLAS FILIPINAS"] },
  '261': { 'code': '261', 'name': ["BORNEO", "BORNEO"] },
  '262': { 'code': '262', 'name': ["CELEBES SEA", "MAR CELEBES"] },
  '263': { 'code': '263', 'name': ["TALAUD ISLANDS, INDONESIA", "ISLAS TALAUD, INDONESIA"] },
  '264': { 'code': '264', 'name': ["NORTH OF HALMAHERA, INDONESIA", "NORTE DE HALMAHERA, INDONESIA"] },
  '265': { 'code': '265', 'name': ["MINAHASSA PENINSULA, SULAWESI", "PENINSULA MINAHASSA, SULAWESI"] },
  '266': { 'code': '266', 'name': ["NORTHERN MOLUCCA SEA", "REGION NORTE DEL MAR MOLUCCA"] },
  '267': { 'code': '267', 'name': ["HALMAHERA, INDONESIA", "HALMAHERA, INDONESIA"] },
  '268': { 'code': '268', 'name': ["SULAWESI, INDONESIA", "SULAWESI, INDONESIA"] },
  '269': { 'code': '269', 'name': ["SOUTHERN MOLUCCA SEA", "REGION SUR DEL MAR MOLUCCA"] },
  '270': { 'code': '270', 'name': ["CERAM SEA", "MAR CERAM"] },
  '271': { 'code': '271', 'name': ["BURU, INDONESIA", "BURU, INDONESIA"] },
  '272': { 'code': '272', 'name': ["SERAM, INDONESIA", "SERAM, INDONESIA"] },
  '273': { 'code': '273', 'name': ["SOUTHWEST OF SUMATERA, INDONESIA", "SUROESTE DE SUMATRA, INDONESIA"] },
  '274': { 'code': '274', 'name': ["SOUTHERN SUMATERA, INDONESIA", "REGION SUR DE SUMATRA, INDONESIA"] },
  '275': { 'code': '275', 'name': ["JAVA SEA", "MAR DE JAVA"] },
  '276': { 'code': '276', 'name': ["SUNDA STRAIT, INDONESIA", "ESTRECHO DE SUNDA, INDONESIA"] },
  '277': { 'code': '277', 'name': ["JAVA, INDONESIA", "JAVA, INDONESIA"] },
  '278': { 'code': '278', 'name': ["BALI SEA", "MAR DE BALI"] },
  '279': { 'code': '279', 'name': ["FLORES SEA", "MAR DE FLORES"] },
  '280': { 'code': '280', 'name': ["BANDA SEA", "MAR DE BANDA"] },
  '281': { 'code': '281', 'name': ["TANIMBAR ISLANDS REG., INDONESIA", "REGION ISLAS TANIMBAR, INDONESIA"] },
  '282': { 'code': '282', 'name': ["SOUTH OF JAVA, INDONESIA", "SUR DE JAVA, INDONESIA"] },
  '283': { 'code': '283', 'name': ["BALI REGION, INDONESIA", "REGION DE BALI, INDONESIA"] },
  '284': { 'code': '284', 'name': ["SOUTH OF BALI, INDONESIA", "SUR DE BALI, INDONESIA"] },
  '285': { 'code': '285', 'name': ["SUMBAWA REGION, INDONESIA", "REGION SUMBAWA, INDONESIA"] },
  '286': { 'code': '286', 'name': ["FLORES REGION, INDONESIA", "REGION DE FLORES, INDONESIA"] },
  '287': { 'code': '287', 'name': ["SUMBA REGION, INDONESIA", "REGION SUMBA, INDONESIA"] },
  '288': { 'code': '288', 'name': ["SAVU SEA", "MAR SAVU"] },
  '289': { 'code': '289', 'name': ["TIMOR REGION", "REGION TIMOR"] },
  '290': { 'code': '290', 'name': ["TIMOR SEA", "MAR TIMOR"] },
  '291': { 'code': '291', 'name': ["SOUTH OF SUMBAWA, INDONESIA", "SUR DE SUMBAWA, INDONESIA"] },
  '292': { 'code': '292', 'name': ["SOUTH OF SUMBA, INDONESIA", "SUR DE SUMBA, INDONESIA"] },
  '293': { 'code': '293', 'name': ["SOUTH OF TIMOR, INDONESIA", "SUR DE TIMOR, INDONESIA"] },
  '294': { 'code': '294', 'name': ["MYANMAR-INDIA BORDER REGION", "REGION FRONTERIZA DE MYANMAR-INDIA"] },
  '295': { 'code': '295', 'name': ["MYANMAR-BANGLADESH BORDER REGION", "REGION FRONTERIZA MYANMAR-BANGLADESH"] },
  '296': { 'code': '296', 'name': ["MYANMAR", "MYANMAR"] },
  '297': { 'code': '297', 'name': ["MYANMAR-CHINA BORDER REGION", "REGION FRONTERIZA MYANMAR-CHINA"] },
  '298': { 'code': '298', 'name': ["NEAR SOUTH COAST OF MYANMAR", "CERCA DE LA COSTA SUR DE MYANMAR"] },
  '299': { 'code': '299', 'name': ["SOUTHEAST ASIA", "SURESTE DE ASIA"] },
  '300': { 'code': '300', 'name': ["HAINAN ISLAND, CHINA", "ISLA HAINAN, CHINA"] },
  '301': { 'code': '301', 'name': ["SOUTH CHINA SEA", "SUR DEL MAR DE CHINA"] },
  '302': { 'code': '302', 'name': ["EASTERN KASHMIR", "REGION ESTE DE KASHMIR"] },
  '303': { 'code': '303', 'name': ["KASHMIR-INDIA BORDER REGION", "REGION FRONTERIZA KASHMIR-INDIA"] },
  '304': { 'code': '304', 'name': ["KASHMIR-XIZANG BORDER REGION", "REGION FRONTERIZA KASHMIR-XIZANG"] },
  '305': { 'code': '305', 'name': ["WESTERN XIZANG-INDIA BORDER REGION", "REGION FRONTERIZA REGION OESTE XIZANG-INDIA"] },
  '306': { 'code': '306', 'name': ["XIZANG", "XIZANG"] },
  '307': { 'code': '307', 'name': ["SICHUAN, CHINA", "SICHUAN, CHINA"] },
  '308': { 'code': '308', 'name': ["NORTHERN INDIA", "REGION NORTE DE INDIA"] },
  '309': { 'code': '309', 'name': ["NEPAL-INDIA BORDER REGION", "REGION FRONTERIZA NEPAL-INDIA"] },
  '310': { 'code': '310', 'name': ["NEPAL", "NEPAL"] },
  '311': { 'code': '311', 'name': ["SIKKIM, INDIA", "SIKKIM, INDIA"] },
  '312': { 'code': '312', 'name': ["BHUTAN", "BHUTAN"] },
  '313': { 'code': '313', 'name': ["EASTERN XIZANG-INDIA BORDER REG.", "REGION FRONTERIZA DE LA REGION ESTE XIZANG-INDIA"] },
  '314': { 'code': '314', 'name': ["SOUTHERN INDIA", "REGION SUR DE INDIA"] },
  '315': { 'code': '315', 'name': ["INDIA-BANGLADESH BORDER REGION", "REGION FRONTERIZA INDIA-BANGLADESH"] },
  '316': { 'code': '316', 'name': ["BANGLADESH", "BANGLADESH"] },
  '317': { 'code': '317', 'name': ["NORTHEASTERN INDIA", "REGION NORESTE DE INDIA"] },
  '318': { 'code': '318', 'name': ["YUNNAN, CHINA", "YUNNAN, CHINA"] },
  '319': { 'code': '319', 'name': ["BAY OF BENGAL", "BAHIA DE BENGAL"] },
  '320': { 'code': '320', 'name': ["KYRGYZSTAN-XINJIANG BORDER REG.", "REGION FRONTERIZA KYRGYZSTAN-XINJIANG"] },
  '321': { 'code': '321', 'name': ["SOUTHERN XINJIANG, CHINA", "REGION SUR DE XINJIANG, CHINA"] },
  '322': { 'code': '322', 'name': ["GANSU, CHINA", "GANSU, CHINA"] },
  '323': { 'code': '323', 'name': ["WESTERN NEI MONGOL, CHINA", "REGION OESTE DE NEI MONGOL, CHINA"] },
  '324': { 'code': '324', 'name': ["KASHMIR-XINJIANG BORDER REGION", "REGION FRONTERIZA KASHMIR-XINJIANG"] },
  '325': { 'code': '325', 'name': ["QINGHAI, CHINA", "QINGHAI, CHINA"] },
  '326': { 'code': '326', 'name': ["SOUTHWESTERN SIBERIA, RUSSIA", "REGION SUROESTE DE SIBERIA, RUSIA"] },
  '327': { 'code': '327', 'name': ["LAKE BAYKAL REGION, RUSSIA", "REGION LAGO BAYKAL, RUSIA"] },
  '328': { 'code': '328', 'name': ["EAST OF LAKE BAYKAL, RUSSIA", "ESTE DEL LAGO BAYKAL, RUSIA"] },
  '329': { 'code': '329', 'name': ["EASTERN KAZAKHSTAN", "REGION ESTE DE KAZAKHSTAN"] },
  '330': { 'code': '330', 'name': ["LAKE ISSYK-KUL REGION", "REGION LAGO ISSYK-KUL"] },
  '331': { 'code': '331', 'name': ["KAZAKHSTAN-XINJIANG BORDER REG.", "REGION FRONTERIZA KAZAKHSTAN-XINJIANG"] },
  '332': { 'code': '332', 'name': ["NORTHERN XINJIANG, CHINA", "REGION NORTE DE XINJIANG, CHINA"] },
  '333': { 'code': '333', 'name': ["RUSSIA-MONGOLIA BORDER REGION", "REGION FRONTERIZA RUSIA-MONGOLIA"] },
  '334': { 'code': '334', 'name': ["MONGOLIA", "MONGOLIA"] },
  '335': { 'code': '335', 'name': ["URAL MOUNTAINS REGION, RUSSIA", "MONTANAS URALES, RUSIA"] },
  '336': { 'code': '336', 'name': ["WESTERN KAZAKHSTAN", "REGION OESTE DE KAZAKHSTAN"] },
  '337': { 'code': '337', 'name': ["EASTERN CAUCASUS", "REGION ESTE DEL CAUCASO"] },
  '338': { 'code': '338', 'name': ["CASPIAN SEA", "MAR CASPIO"] },
  '339': { 'code': '339', 'name': ["NORTHWESTERN UZBEKISTAN", "REGION NOROESTE DE UZBEKISTAN"] },
  '340': { 'code': '340', 'name': ["TURKMENISTAN", "TURKMENISTAN"] },
  '341': { 'code': '341', 'name': ["TURKMENISTAN-IRAN BORDER REGION", "REGION FRONTERIZA TURKMENISTAN-IRAN"] },
  '342': { 'code': '342', 'name': ["TURKMENISTAN-AFGHANISTAN BRD REG", "REGION FRONTERIZA TURKMENISTAN-AFGHANISTAN"] },
  '343': { 'code': '343', 'name': ["TURKEY-IRAN BORDER REGION", "REGION FRONTERIZA TURQUIA-IRAN"] },
  '344': { 'code': '344', 'name': ["ARMENIA-AZERBAIJAN-IRAN BORD REG", "REGION FRONTERIZA ARMENIA-AZERBAIJAN-IRAN"] },
  '345': { 'code': '345', 'name': ["NORTHWESTERN IRAN", "REGION NOROESTE DE IRAN"] },
  '346': { 'code': '346', 'name': ["IRAN-IRAQ BORDER REGION", "REGION FRONTERIZA IRAN-IRAQ"] },
  '347': { 'code': '347', 'name': ["WESTERN IRAN", "REGION OESTE DE IRAN"] },
  '348': { 'code': '348', 'name': ["NORTHERN AND CENTRAL IRAN", "REGION NORTE Y CENTRAL DE IRAN"] },
  '349': { 'code': '349', 'name': ["NORTHWESTERN AFGHANISTAN", "REGION NOROESTE DE AFGHANISTAN"] },
  '350': { 'code': '350', 'name': ["SOUTHWESTERN AFGHANISTAN", "REGION SUROESTE DE AFGHANISTAN"] },
  '351': { 'code': '351', 'name': ["EASTERN ARABIAN PENINSULA", "REGION ESTE DE LA PENINSULA ARABIGA"] },
  '352': { 'code': '352', 'name': ["PERSIAN GULF", "GOLFO PERSICO"] },
  '353': { 'code': '353', 'name': ["SOUTHERN IRAN", "REGION SUR DE IRAN"] },
  '354': { 'code': '354', 'name': ["SOUTHWESTERN PAKISTAN", "REGION SUROESTE DE PAKISTAN"] },
  '355': { 'code': '355', 'name': ["GULF OF OMAN", "GOLFO DE OMAN"] },
  '356': { 'code': '356', 'name': ["OFF COAST OF PAKISTAN", "FUERA DE LA COSTA DE PAKISTAN"] },
  '357': { 'code': '357', 'name': ["UKRAINE-MOLDOVA-SW RUSSIA REGION", "REGION SUROESTE DE UCRANIA-MOLDAVIA, RUSIA"] },
  '358': { 'code': '358', 'name': ["ROMANIA", "RUMANIA"] },
  '359': { 'code': '359', 'name': ["BULGARIA", "BULGARIA"] },
  '360': { 'code': '360', 'name': ["BLACK SEA", "MAR NEGRO"] },
  '361': { 'code': '361', 'name': ["CRIMEA REGION, UKRAINE", "REGION CRIMEA, UCRANIA"] },
  '362': { 'code': '362', 'name': ["WESTERN CAUCASUS", "REGION OESTE DEL CAUCASO"] },
  '363': { 'code': '363', 'name': ["GREECE-BULGARIA BORDER REGION", "REGION FRONTERIZA DE GREECIA-BULGARIA"] },
  '364': { 'code': '364', 'name': ["GREECE", "GRECIA"] },
  '365': { 'code': '365', 'name': ["AEGEAN SEA", "MAR EGEO"] },
  '366': { 'code': '366', 'name': ["TURKEY", "TURQUIA"] },
  '367': { 'code': '367', 'name': ["GEORGIA-ARMENIA-TURKEY BORD REG.", "REGION FRONTERIZA DE GEORGIA-ARMENIA-TURQUIA"] },
  '368': { 'code': '368', 'name': ["SOUTHERN GREECE", "REGION SUR DE GRECIA"] },
  '369': { 'code': '369', 'name': ["DODECANESE ISLANDS, GREECE", "ISLAS DODECANESE, GRECIA"] },
  '370': { 'code': '370', 'name': ["CRETE, GREECE", "CRETA, GRECIA"] },
  '371': { 'code': '371', 'name': ["EASTERN MEDITERRANEAN SEA", "REGION ESTE DEL MAR MEDITERRANEO"] },
  '372': { 'code': '372', 'name': ["CYPRUS REGION", "REGION DE CHIPRE"] },
  '373': { 'code': '373', 'name': ["DEAD SEA REGION", "REGION DEL MAR MUERTO"] },
  '374': { 'code': '374', 'name': ["JORDAN - SYRIA REGION", "REGION JORDAN-SYRIA"] },
  '375': { 'code': '375', 'name': ["IRAQ", "IRAQ"] },
  '376': { 'code': '376', 'name': ["PORTUGAL", "PORTUGAL"] },
  '377': { 'code': '377', 'name': ["SPAIN", "ESPANA"] },
  '378': { 'code': '378', 'name': ["PYRENEES", "PIRINEOS"] },
  '379': { 'code': '379', 'name': ["NEAR SOUTH COAST OF FRANCE", "CERCA DE LA COSTA SUR DE FRANCIA"] },
  '380': { 'code': '380', 'name': ["CORSICA, FRANCE", "CORSICA, FRANCIA"] },
  '381': { 'code': '381', 'name': ["CENTRAL ITALY", "CENTRO DE ITALIA"] },
  '382': { 'code': '382', 'name': ["ADRIATIC SEA", "MAR ADRIATICO"] },
  '383': { 'code': '383', 'name': ["NORTHWESTERN BALKAN REGION", "REGION NOROESTE DE LA REGION DE BALCANES"] },
  '384': { 'code': '384', 'name': ["WEST OF GIBRALTAR", "OESTE DE GIBRALTAR"] },
  '385': { 'code': '385', 'name': ["STRAIT OF GIBRALTAR", "ESTRECHO DE GIBRALTAR"] },
  '386': { 'code': '386', 'name': ["BALEARIC ISLANDS, SPAIN", "ISLAS BALEARES, ESPANA"] },
  '387': { 'code': '387', 'name': ["WESTERN MEDITERRANEAN SEA", "REGION OESTE DEL MAR MEDITERRANEO"] },
  '388': { 'code': '388', 'name': ["SARDINIA, ITALY", "SARDINIA, ITALIA"] },
  '389': { 'code': '389', 'name': ["TYRRHENIAN SEA", "MAR DE TYRRHENIAN"] },
  '390': { 'code': '390', 'name': ["SOUTHERN ITALY", "REGION SUR DE ITALIA"] },
  '391': { 'code': '391', 'name': ["ALBANIA", "ALBANIA"] },
  '392': { 'code': '392', 'name': ["GREECE-ALBANIA BORDER REGION", "REGION FRONTERIZA GRECIA ALBANIA"] },
  '393': { 'code': '393', 'name': ["MADEIRA ISLANDS, PORTUGAL REGION", "ISLAS MADEIRA, REGION DE PORTUGAL"] },
  '394': { 'code': '394', 'name': ["CANARY ISLANDS, SPAIN REGION", "ISLAS CANARIAS, REGION DE ESPANA"] },
  '395': { 'code': '395', 'name': ["MOROCCO", "MARRUECOS"] },
  '396': { 'code': '396', 'name': ["NORTHERN ALGERIA", "REGION NORTE DE ALGERIA"] },
  '397': { 'code': '397', 'name': ["TUNISIA", "TUNISIA"] },
  '398': { 'code': '398', 'name': ["SICILY, ITALY", "SICILIA, ITALIA"] },
  '399': { 'code': '399', 'name': ["IONIAN SEA", "MAR IONEAN"] },
  '400': { 'code': '400', 'name': ["CENTRAL MEDITERRANEAN SEA", "CENTRO MAR MEDITERRANEO"] },
  '401': { 'code': '401', 'name': ["NEAR COAST OF LIBYA", "CERCA DE LA COSTA DE LIBIA"] },
  '402': { 'code': '402', 'name': ["NORTH ATLANTIC OCEAN", "OCEANO ATLANTICO NORTE"] },
  '403': { 'code': '403', 'name': ["NORTHERN MID-ATLANTIC RIDGE", "REGION NORTE DE LA DORSAL MESOCEANICA"] },
  '404': { 'code': '404', 'name': ["AZORES ISLANDS REGION", "REGION ISLAS AZORES"] },
  '405': { 'code': '405', 'name': ["AZORES ISLANDS, PORTUGAL", "ISLAS AZORES, PORTUGAL"] },
  '406': { 'code': '406', 'name': ["CENTRAL MID-ATLANTIC RIDGE", "CENTRO DORSAL MESOCEANICA"] },
  '407': { 'code': '407', 'name': ["NORTH OF ASCENSION ISLAND", "NORTE DE LA ISLA ASCENCION"] },
  '408': { 'code': '408', 'name': ["ASCENSION ISLAND REGION", "REGION DE LA ISLA ASCENCION"] },
  '409': { 'code': '409', 'name': ["SOUTH ATLANTIC OCEAN", "OCEANO ATLANTICO SUR"] },
  '410': { 'code': '410', 'name': ["SOUTHERN MID-ATLANTIC RIDGE", "REGION SUR DE LA DORSAL MESOCEANICA"] },
  '411': { 'code': '411', 'name': ["TRISTAN DA CUNHA REGION", "REGION TRISTAN DA CUNHA"] },
  '412': { 'code': '412', 'name': ["BOUVET ISLAND REGION", "REGION ISLA BOUVET"] },
  '413': { 'code': '413', 'name': ["SOUTHWEST OF AFRICA", "SUROESTE DE AFRICA"] },
  '414': { 'code': '414', 'name': ["SOUTHEASTERN ATLANTIC OCEAN", "REGION SURESTE DEL OCEANO ATLANTICO"] },
  '415': { 'code': '415', 'name': ["EASTERN GULF OF ADEN", "REGION ESTE DEL GOLFO DE ADEN"] },
  '416': { 'code': '416', 'name': ["SOCOTRA REGION", "REGION DE SOCOTRA"] },
  '417': { 'code': '417', 'name': ["ARABIAN SEA", "MAR ARABIGO"] },
  '418': { 'code': '418', 'name': ["LAKSHADWEEP REGION, INDIA", "REGION LAKSHADWEEP, INDIA"] },
  '419': { 'code': '419', 'name': ["NORTHEASTERN SOMALIA", "REGION NORESTE DE SOMALIA"] },
  '420': { 'code': '420', 'name': ["NORTH INDIAN OCEAN", "OCEANO INDICO NORTE"] },
  '421': { 'code': '421', 'name': ["CARLSBERG RIDGE", "CORDILLERA CARLSBERG"] },
  '422': { 'code': '422', 'name': ["MALDIVE ISLANDS REGION", "REGION DE LAS ISLAS MALDIVAS"] },
  '423': { 'code': '423', 'name': ["LACCADIVE SEA", "MAR DE LACCADIVE"] },
  '424': { 'code': '424', 'name': ["SRI LANKA", "SRI LANKA"] },
  '425': { 'code': '425', 'name': ["SOUTH INDIAN OCEAN", "OCEANO INDICO SUR"] },
  '426': { 'code': '426', 'name': ["CHAGOS ARCHIPELAGO REGION", "REGION DEL ARCHIPIELAGO CHAGOS"] },
  '427': { 'code': '427', 'name': ["MAURITIUS - REUNION REGION", "REGION MAURITUS-REUNION"] },
  '428': { 'code': '428', 'name': ["SOUTHWEST INDIAN RIDGE", "SUROESTE DE CORDILLERA INDIA"] },
  '429': { 'code': '429', 'name': ["MID-INDIAN RIDGE", "CORDILLERA MEDIA INDICA"] },
  '430': { 'code': '430', 'name': ["SOUTH OF AFRICA", "SUR DE AFRICA"] },
  '431': { 'code': '431', 'name': ["PRINCE EDWARD ISLANDS REGION", "REGION DE LAS ISLAS PRINCE EDWARD"] },
  '432': { 'code': '432', 'name': ["CROZET ISLANDS REGION", "REGION DE LAS ISLAS CROZET"] },
  '433': { 'code': '433', 'name': ["KERGUELEN ISLANDS REGION", "REGION DE LAS ISLAS KERGUELEN"] },
  '434': { 'code': '434', 'name': ["BROKEN RIDGE", "CORDILLERA BROKEN"] },
  '435': { 'code': '435', 'name': ["SOUTHEAST INDIAN RIDGE", "SURESTE DE LA CORDILLERA INDICA"] },
  '436': { 'code': '436', 'name': ["SOUTHERN KERGUELEN PLATEAU", "REGION SUR DE LA MESETA KERGUELEN"] },
  '437': { 'code': '437', 'name': ["SOUTH OF AUSTRALIA", "SUR DE AUSTRALIA"] },
  '438': { 'code': '438', 'name': ["SASKATCHEWAN, CANADA", "SASKATCHEWAN, CANADA"] },
  '439': { 'code': '439', 'name': ["MANITOBA, CANADA", "MANITOBA, CANADA"] },
  '440': { 'code': '440', 'name': ["HUDSON BAY", "BAHIA DE HUDSON"] },
  '441': { 'code': '441', 'name': ["ONTARIO, CANADA", "ONTARIO, CANADA"] },
  '442': { 'code': '442', 'name': ["HUDSON STRAIT REGION, CANADA", "REGION DE HUDSON STRAIT, CANADA"] },
  '443': { 'code': '443', 'name': ["NORTHERN QUEBEC, CANADA", "REGION NORTE DE QUEBEC, CANADA"] },
  '444': { 'code': '444', 'name': ["DAVIS STRAIT", "ESTRECHO DE DAVIS"] },
  '445': { 'code': '445', 'name': ["LABRADOR, CANADA", "LABRADOR, CANADA"] },
  '446': { 'code': '446', 'name': ["LABRADOR SEA", "MAR DE LABRADOR"] },
  '447': { 'code': '447', 'name': ["SOUTHERN QUEBEC, CANADA", "REGION SUR DE QUEBEC, CANADA"] },
  '448': { 'code': '448', 'name': ["GASPE PENINSULA, CANADA", "PENINSULA DE GASPE, CANADA"] },
  '449': { 'code': '449', 'name': ["EASTERN QUEBEC, CANADA", "REGION ESTE DE QUEBEC, CANADA"] },
  '450': { 'code': '450', 'name': ["ANTICOSTI ISLAND, CANADA", "ISLA ANTICOSTI, CANADA"] },
  '451': { 'code': '451', 'name': ["NEW BRUNSWICK, CANADA", "NEW BRUNSWICK, CANADA"] },
  '452': { 'code': '452', 'name': ["NOVA SCOTIA, CANADA", "NUEVA ESCOCIA, CANADA"] },
  '453': { 'code': '453', 'name': ["PRINCE EDWARD ISLAND, CANADA", "ISLA PRINCE EDWARD, CANADA"] },
  '454': { 'code': '454', 'name': ["GULF OF ST. LAWRENCE", "GOLFO DE ST. LAWRENCE"] },
  '455': { 'code': '455', 'name': ["NEWFOUNDLAND, CANADA", "NEWFOUNDLAND, CANADA"] },
  '456': { 'code': '456', 'name': ["MONTANA", "MONTANA"] },
  '457': { 'code': '457', 'name': ["EASTERN IDAHO", "REGION ESTE DE IDAHO"] },
  '458': { 'code': '458', 'name': ["HEBGEN LAKE REGION", "REGION DEL LAGO HEBGEN"] },
  '459': { 'code': '459', 'name': ["YELLOWSTONE REGION, WYOMING", "REGION DE YELLOWSTONE, WYOMING"] },
  '460': { 'code': '460', 'name': ["WYOMING", "WYOMING"] },
  '461': { 'code': '461', 'name': ["NORTH DAKOTA", "DAKOTA DEL NORTE"] },
  '462': { 'code': '462', 'name': ["SOUTH DAKOTA", "DAKOTA DEL SUR"] },
  '463': { 'code': '463', 'name': ["NEBRASKA", "NEBRASKA"] },
  '464': { 'code': '464', 'name': ["MINNESOTA", "MINNESOTA"] },
  '465': { 'code': '465', 'name': ["IOWA", "IOWA"] },
  '466': { 'code': '466', 'name': ["WISCONSIN", "WISCONSIN"] },
  '467': { 'code': '467', 'name': ["ILLINOIS", "ILLINOIS"] },
  '468': { 'code': '468', 'name': ["MICHIGAN", "MICHIGAN"] },
  '469': { 'code': '469', 'name': ["INDIANA", "INDIANA"] },
  '470': { 'code': '470', 'name': ["SOUTHERN ONTARIO, CANADA", "REGION SUR DE ONTARIO, CANADA"] },
  '471': { 'code': '471', 'name': ["OHIO", "OHIO"] },
  '472': { 'code': '472', 'name': ["NEW YORK", "NEW YORK"] },
  '473': { 'code': '473', 'name': ["PENNSYLVANIA", "PENNSYLVANIA"] },
  '474': { 'code': '474', 'name': ["VERMONT - NEW HAMPSHIRE REGION", "REGION VERMONT - NEW HAMPSHIRE"] },
  '475': { 'code': '475', 'name': ["MAINE", "MAINE"] },
  '476': { 'code': '476', 'name': ["SOUTHERN NEW ENGLAND", "REGION SUR THE NUEVA INGLATERRA"] },
  '477': { 'code': '477', 'name': ["GULF OF MAINE", "GOLFO DE MAINE"] },
  '478': { 'code': '478', 'name': ["UTAH", "UTAH"] },
  '479': { 'code': '479', 'name': ["COLORADO", "COLORADO"] },
  '480': { 'code': '480', 'name': ["KANSAS", "KANSAS"] },
  '481': { 'code': '481', 'name': ["IOWA-MISSOURI BORDER REGION", "REGION FRONTERIZA IOWA-MISSOURI"] },
  '482': { 'code': '482', 'name': ["MISSOURI-KANSAS BORDER REGION", "REGION FRONTERIZA MISSOURI-KANSAS"] },
  '483': { 'code': '483', 'name': ["MISSOURI", "MISSOURI"] },
  '484': { 'code': '484', 'name': ["MISSOURI-ARKANSAS BORDER REGION", "REGION FRONTERIZA MISSOURI-ARKANSAS"] },
  '485': { 'code': '485', 'name': ["EASTERN MISSOURI", "REGION ESTE DE MISSOURI"] },
  '486': { 'code': '486', 'name': ["NEW MADRID, MISSOURI  REGION", "NUEVO MADRID, REGION DE MISSOURI"] },
  '487': { 'code': '487', 'name': ["CAPE GIRARDEAU, MISSOURI  REGION", "CABO GIRARDEAU, REGION DE MISSOURI"] },
  '488': { 'code': '488', 'name': ["SOUTHERN ILLINOIS", "REGION SUR ILLINOIS"] },
  '489': { 'code': '489', 'name': ["SOUTHERN INDIANA", "REGION SUR DE INDIANA"] },
  '490': { 'code': '490', 'name': ["KENTUCKY", "KENTUCKY"] },
  '491': { 'code': '491', 'name': ["WEST VIRGINIA", "WEST VIRGINIA"] },
  '492': { 'code': '492', 'name': ["VIRGINIA", "VIRGINIA"] },
  '493': { 'code': '493', 'name': ["CHESAPEAKE BAY REGION", "REGION DE LA BAHIA DE CHESAPEAKE"] },
  '494': { 'code': '494', 'name': ["NEW JERSEY", "NEW JERSEY"] },
  '495': { 'code': '495', 'name': ["EASTERN ARIZONA", "REGION ESTE DE ARIZONA"] },
  '496': { 'code': '496', 'name': ["NEW MEXICO", "NUEVO MEXICO"] },
  '497': { 'code': '497', 'name': ["TEXAS PANHANDLE REGION", "REGION DE PANHANDLE, TEXAS"] },
  '498': { 'code': '498', 'name': ["WESTERN TEXAS", "REGION OESTE DE TEXAS"] },
  '499': { 'code': '499', 'name': ["OKLAHOMA", "OKLAHOMA"] },
  '500': { 'code': '500', 'name': ["CENTRAL TEXAS", "CENTRO DE TEXAS"] },
  '501': { 'code': '501', 'name': ["ARKANSAS-OKLAHOMA BORDER REGION", "REGION FRONTERIZA ARKANSAS-OKLAHOMA"] },
  '502': { 'code': '502', 'name': ["ARKANSAS", "ARKANSAS"] },
  '503': { 'code': '503', 'name': ["LOUISIANA-TEXAS BORDER REGION", "REGION FRONTERIZA LOUISIANA-TEXAS"] },
  '504': { 'code': '504', 'name': ["LOUISIANA", "LOUISIANA"] },
  '505': { 'code': '505', 'name': ["MISSISSIPPI", "MISSISSIPPI"] },
  '506': { 'code': '506', 'name': ["TENNESSEE", "TENNESSEE"] },
  '507': { 'code': '507', 'name': ["ALABAMA", "ALABAMA"] },
  '508': { 'code': '508', 'name': ["WESTERN FLORIDA", "REGION OESTE DE FLORIDA"] },
  '509': { 'code': '509', 'name': ["GEORGIA, USA", "GEORGIA, EU"] },
  '510': { 'code': '510', 'name': ["FLORIDA-GEORGIA BORDER REGION", "REGION FRONTERIZA FLORIDA-GEORGIA"] },
  '511': { 'code': '511', 'name': ["SOUTH CAROLINA", "SOUTH CAROLINA"] },
  '512': { 'code': '512', 'name': ["NORTH CAROLINA", "NORTH CAROLINA"] },
  '513': { 'code': '513', 'name': ["OFF EAST COAST OF UNITED STATES", "FUERA DE LA COSTA ESTE DE LOS EU"] },
  '514': { 'code': '514', 'name': ["FLORIDA PENINSULA", "PENINSULA DE FLORIDA"] },
  '515': { 'code': '515', 'name': ["BAHAMA ISLANDS", "ISLAS BAHAMAS"] },
  '516': { 'code': '516', 'name': ["E. ARIZONA-SONORA BORDER REGION", "REGION FRONTERIZA ESTE ARIZONA-SONORA"] },
  '517': { 'code': '517', 'name': ["NEW MEXICO-CHIHUAHUA BORDER REG.", "REGION FRONTERIZA NUEVO MEXICO-CHIHUAHUA"] },
  '518': { 'code': '518', 'name': ["TEXAS-MEXICO BORDER REGION", "REGION FRONTERIZA TEXAS-MEXICO"] },
  '519': { 'code': '519', 'name': ["SOUTHERN TEXAS", "REGION SUR DE TEXAS"] },
  '520': { 'code': '520', 'name': ["NEAR COAST OF TEXAS", "CERCA DE LA COSTA DE TEXAS"] },
  '521': { 'code': '521', 'name': ["CHIHUAHUA, MEXICO", "CHIHUAHUA, MEXICO"] },
  '522': { 'code': '522', 'name': ["NORTHERN MEXICO", "REGION NORTE DE MEXICO"] },
  '523': { 'code': '523', 'name': ["CENTRAL MEXICO", "CENTRO DE MEXICO"] },
  '524': { 'code': '524', 'name': ["JALISCO, MEXICO", "JALISCO, MEXICO"] },
  '525': { 'code': '525', 'name': ["VERACRUZ, MEXICO", "VERACRUZ, MEXICO"] },
  '526': { 'code': '526', 'name': ["GULF OF MEXICO", "GOLFO DE MEXICO"] },
  '527': { 'code': '527', 'name': ["BAY OF CAMPECHE", "BAHIA DE CAMPECHE"] },
  '528': { 'code': '528', 'name': ["BRAZIL", "BRASIL"] },
  '529': { 'code': '529', 'name': ["GUYANA", "GUYANA"] },
  '530': { 'code': '530', 'name': ["SURINAME", "SURINAM"] },
  '531': { 'code': '531', 'name': ["FRENCH GUIANA", "GUYANA FRANCESA"] },
  '532': { 'code': '532', 'name': ["IRELAND", "IRLANDA"] },
  '533': { 'code': '533', 'name': ["UNITED KINGDOM", "REINO UNIDO"] },
  '534': { 'code': '534', 'name': ["NORTH SEA", "MAR DEL NORTE"] },
  '535': { 'code': '535', 'name': ["SOUTHERN NORWAY", "REGION SUR DE NORUEGA"] },
  '536': { 'code': '536', 'name': ["SWEDEN", "SUECIA"] },
  '537': { 'code': '537', 'name': ["BALTIC SEA", "MAR BALTICO"] },
  '538': { 'code': '538', 'name': ["FRANCE", "FRANCIA"] },
  '539': { 'code': '539', 'name': ["BAY OF BISCAY", "BAHIA DE BISCAY"] },
  '540': { 'code': '540', 'name': ["THE NETHERLANDS", "PAISES BAJOS"] },
  '541': { 'code': '541', 'name': ["BELGIUM", "BELGICA"] },
  '542': { 'code': '542', 'name': ["DENMARK", "DINAMARCA"] },
  '543': { 'code': '543', 'name': ["GERMANY", "ALEMANIA"] },
  '544': { 'code': '544', 'name': ["SWITZERLAND", "SUIZA"] },
  '545': { 'code': '545', 'name': ["NORTHERN ITALY", "REGION NORTE DE ITALIA"] },
  '546': { 'code': '546', 'name': ["AUSTRIA", "AUSTRIA"] },
  '547': { 'code': '547', 'name': ["CZECH AND SLOVAK REPUBLICS", "REPUBLICAS CHECA Y ESLOVACA"] },
  '548': { 'code': '548', 'name': ["POLAND", "POLONIA"] },
  '549': { 'code': '549', 'name': ["HUNGARY", "HUNGRIA"] },
  '550': { 'code': '550', 'name': ["NORTHWEST AFRICA", "NOROESTE DE AFRICA"] },
  '551': { 'code': '551', 'name': ["SOUTHERN ALGERIA", "REGION SUR DE ALGERIA"] },
  '552': { 'code': '552', 'name': ["LIBYA", "LIBIA"] },
  '553': { 'code': '553', 'name': ["EGYPT", "EGIPTO"] },
  '554': { 'code': '554', 'name': ["RED SEA", "MAR ROJO"] },
  '555': { 'code': '555', 'name': ["WESTERN ARABIAN PENINSULA", "REGION OESTE DE LA PENINSULA ARABIGA"] },
  '556': { 'code': '556', 'name': ["CHAD REGION", "REGION DE CHAD"] },
  '557': { 'code': '557', 'name': ["SUDAN", "SUDAN"] },
  '558': { 'code': '558', 'name': ["ETHIOPIA", "ETIOPIA"] },
  '559': { 'code': '559', 'name': ["WESTERN GULF OF ADEN", "REGION OESTE DEL GOLFO DE ADEN"] },
  '560': { 'code': '560', 'name': ["NORTHWESTERN SOMALIA", "REGION NOROESTE DE SOMALIA"] },
  '561': { 'code': '561', 'name': ["OFF S. COAST OF NORTHWEST AFRICA", "FUERA DE LA COSTA SUR DEL NOROESTE DE AFRICA"] },
  '562': { 'code': '562', 'name': ["CAMEROON", "CAMEROON"] },
  '563': { 'code': '563', 'name': ["EQUATORIAL GUINEA", "GUINEA ECUATORIAL"] },
  '564': { 'code': '564', 'name': ["CENTRAL AFRICAN REPUBLIC", "REPUBLICA CENTRAL AFRICANA"] },
  '565': { 'code': '565', 'name': ["GABON", "GABON"] },
  '566': { 'code': '566', 'name': ["REPUBLIC OF CONGO", "REPUBLICA DEL CONGO"] },
  '567': { 'code': '567', 'name': ["DEMOCRATIC REPUBLIC OF CONGO", "REPUBLICA DEMOCRATICA DEL CONGO"] },
  '568': { 'code': '568', 'name': ["UGANDA", "UGANDA"] },
  '569': { 'code': '569', 'name': ["LAKE VICTORIA REGION", "REGION DEL LAGO VICTORIA"] },
  '570': { 'code': '570', 'name': ["KENYA", "KENYA"] },
  '571': { 'code': '571', 'name': ["SOUTHERN SOMALIA", "REGION SUR DE SOMALIA"] },
  '572': { 'code': '572', 'name': ["LAKE TANGANYIKA REGION", "REGION DEL LAGO TANGANYIKA"] },
  '573': { 'code': '573', 'name': ["TANZANIA", "TANZANIA"] },
  '574': { 'code': '574', 'name': ["NORTHWEST OF MADAGASCAR", "NOROESTE DE MADAGASCAR"] },
  '575': { 'code': '575', 'name': ["ANGOLA", "ANGOLA"] },
  '576': { 'code': '576', 'name': ["ZAMBIA", "ZAMBIA"] },
  '577': { 'code': '577', 'name': ["MALAWI", "MALAWI"] },
  '578': { 'code': '578', 'name': ["NAMIBIA", "NAMIBIA"] },
  '579': { 'code': '579', 'name': ["BOTSWANA", "BOTSWANA"] },
  '580': { 'code': '580', 'name': ["ZIMBABWE", "ZIMBABWE"] },
  '581': { 'code': '581', 'name': ["MOZAMBIQUE", "MOZAMBIQUE"] },
  '582': { 'code': '582', 'name': ["MOZAMBIQUE CHANNEL", "CANAL DE MOZAMBIQUE"] },
  '583': { 'code': '583', 'name': ["MADAGASCAR", "MADAGASCAR"] },
  '584': { 'code': '584', 'name': ["SOUTH AFRICA", "SURAFRICA"] },
  '585': { 'code': '585', 'name': ["LESOTHO", "LESOTHO"] },
  '586': { 'code': '586', 'name': ["SWAZILAND", "SWAZILAND"] },
  '587': { 'code': '587', 'name': ["OFF COAST OF SOUTH AFRICA", "FUERA DE LA COSTA DE SUR AFRICA"] },
  '588': { 'code': '588', 'name': ["NORTHWEST OF AUSTRALIA", "NOROESTE DE AUSTRALIA"] },
  '589': { 'code': '589', 'name': ["WEST OF AUSTRALIA", "OESTE DE AUSTRALIA"] },
  '590': { 'code': '590', 'name': ["WESTERN AUSTRALIA", "REGION OESTE DE AUSTRALIA"] },
  '591': { 'code': '591', 'name': ["NORTHERN TERRITORY, AUSTRALIA", "TERRITORIO DE LA REGION NORTE, AUSTRALIA"] },
  '592': { 'code': '592', 'name': ["SOUTH AUSTRALIA", "SUR DE AUSTRALIA"] },
  '593': { 'code': '593', 'name': ["GULF OF CARPENTARIA", "GOLFO DE CARPENTARIA"] },
  '594': { 'code': '594', 'name': ["QUEENSLAND, AUSTRALIA", "QUEENSLAND, AUSTRALIA"] },
  '595': { 'code': '595', 'name': ["CORAL SEA", "MAR CORAL"] },
  '596': { 'code': '596', 'name': ["NORTHWEST OF NEW CALEDONIA", "NOROESTE DE NUEVA CALEDONIA"] },
  '597': { 'code': '597', 'name': ["SOUTHWEST OF NEW CALEDONIA", "SUROESTE DE NUEVA CALEDONIA"] },
  '598': { 'code': '598', 'name': ["SOUTHWEST OF AUSTRALIA", "SUROESTE DE AUSTRALIA"] },
  '599': { 'code': '599', 'name': ["OFF SOUTH COAST OF AUSTRALIA", "FUERA DE LA COSTA SUR DE AUSTRALIA"] },
  '600': { 'code': '600', 'name': ["NEAR COAST OF SOUTH AUSTRALIA", "CERCA DE LA COSTA SUR DE AUSTRALIA"] },
  '601': { 'code': '601', 'name': ["NEW SOUTH WALES, AUSTRALIA", "NUEVO GALES DEL SUR, AUSTRALIA"] },
  '602': { 'code': '602', 'name': ["VICTORIA, AUSTRALIA", "VICTORIA, AUSTRALIA"] },
  '603': { 'code': '603', 'name': ["NEAR S.E. COAST OF AUSTRALIA", "CERCA DE LA COSTA SURESTE DE AUSTRALIA"] },
  '604': { 'code': '604', 'name': ["NEAR EAST COAST OF AUSTRALIA", "CERCA DE LA COSTA ESTE DE AUSTRALIA"] },
  '605': { 'code': '605', 'name': ["EAST OF AUSTRALIA", "ESTE DE AUSTRALIA"] },
  '606': { 'code': '606', 'name': ["NORFOLK ISLAND REGION", "REGION DE LA ISLA NORFOLK"] },
  '607': { 'code': '607', 'name': ["NORTHWEST OF NEW ZEALAND", "NOROESTE DE NUEVA ZELANDA"] },
  '608': { 'code': '608', 'name': ["BASS STRAIT", "ESTRECHO DE BASS"] },
  '609': { 'code': '609', 'name': ["TASMANIA REGION, AUSTRALIA REGION", "REGION DE TASMANIA, REGION DE AUSTRALIA"] },
  '610': { 'code': '610', 'name': ["SOUTHEAST OF AUSTRALIA", "SURESTE DE AUSTRALIA"] },
  '611': { 'code': '611', 'name': ["NORTH PACIFIC OCEAN", "OCEANO PACIFICO NORTE"] },
  '612': { 'code': '612', 'name': ["HAWAIIAN ISLANDS REGION", "REGION ISLAS HAWAII"] },
  '613': { 'code': '613', 'name': ["HAWAII", "HAWAII"] },
  '614': { 'code': '614', 'name': ["E. CAROLINE ISLANDS, MICRONESIA", "ESTE DE LAS ISLAS CAROLINE, MICRONESIA"] },
  '615': { 'code': '615', 'name': ["MARSHALL ISLANDS REGION", "REGION DE LAS ISLAS MARSHALL"] },
  '616': { 'code': '616', 'name': ["ENEWETAK ATOLL REG, MARSHALL IS.", "REGION DEL ATOLON ENEWETAK, ISLAS MARSHALL"] },
  '617': { 'code': '617', 'name': ["BIKINI ATOLL REG., MARSHALL IS.", "REGION DEL ATOLON BIKINI, ISLAS MARSHALL"] },
  '618': { 'code': '618', 'name': ["GILBERT ISLANDS, KIRIBATI REGION", "ISLAS GILBERT, REGION KIRIBATI"] },
  '619': { 'code': '619', 'name': ["JOHNSTON ISLAND REGION", "REGION ISLA JOHNSTON"] },
  '620': { 'code': '620', 'name': ["LINE ISLANDS REGION, KIRIBATI", "REGION ISLAS LINE, KARIBATI"] },
  '621': { 'code': '621', 'name': ["PALMYRA ISLAND REGION, KIRIBATI", "REGION ISLA PALMYRA, KIRIBATI"] },
  '622': { 'code': '622', 'name': ["KIRITIMATI REGION, KIRIBATI", "REGION KIRIBATI, KIRIBATI"] },
  '623': { 'code': '623', 'name': ["TUVALU REGION", "REGION TUVALU"] },
  '624': { 'code': '624', 'name': ["PHOENIX ISLANDS, KIRIBATI REGION", "ISLAS PHOENIX, REGION KIRIBATI"] },
  '625': { 'code': '625', 'name': ["TOKELAU ISLANDS REGION", "REGION DE LAS ISLAS TOKELAU"] },
  '626': { 'code': '626', 'name': ["NORTHERN COOK ISLANDS", "REGION ESTE DE LAS ISLAS COOK"] },
  '627': { 'code': '627', 'name': ["COOK ISLANDS REGION", "REGION DE LAS ISLAS COOK"] },
  '628': { 'code': '628', 'name': ["SOCIETY ISLANDS REGION", "REGION DE LAS ISLAS SOCIETY"] },
  '629': { 'code': '629', 'name': ["TUBUAI ISLANDS REGION", "REGION DE LAS ISLAS TUBUAI"] },
  '630': { 'code': '630', 'name': ["MARQUESAS ISLANDS REGION", "REGION DE LAS ISLAS MARQUESAS"] },
  '631': { 'code': '631', 'name': ["TUAMOTU ARCHIPELAGO REGION", "REGION DEL ARCHIPIELAGO DE TUAMOTU"] },
  '632': { 'code': '632', 'name': ["SOUTH PACIFIC OCEAN", "OCEANO PACIFICO SUR"] },
  '633': { 'code': '633', 'name': ["LOMONOSOV RIDGE", "CORDILLERA LOMONOSOV"] },
  '634': { 'code': '634', 'name': ["ARCTIC OCEAN", "OCEANO ARTICO"] },
  '635': { 'code': '635', 'name': ["NEAR NORTH COAST OF GREENLAND", "CERCA DE LA COSTA DE GROENLANDIA"] },
  '636': { 'code': '636', 'name': ["EASTERN GREENLAND", "REGION ESTE DE GROENLANDIA"] },
  '637': { 'code': '637', 'name': ["ICELAND REGION", "REGION DE ISLANDIA"] },
  '638': { 'code': '638', 'name': ["ICELAND", "ISLANDIA"] },
  '639': { 'code': '639', 'name': ["JAN MAYEN ISLAND REGION", "REGION ISLA JAN MAYEN"] },
  '640': { 'code': '640', 'name': ["GREENLAND SEA", "MAR DE GROENLANDIA"] },
  '641': { 'code': '641', 'name': ["NORTH OF SVALBARD", "NORTE DE SVALBARD"] },
  '642': { 'code': '642', 'name': ["NORWEGIAN SEA", "MAR NORUEGO"] },
  '643': { 'code': '643', 'name': ["SVALBARD REGION", "REGION DE SVALBARD"] },
  '644': { 'code': '644', 'name': ["NORTH OF FRANZ JOSEF LAND", "NORTE DE FRANZ JOSEF LAND"] },
  '645': { 'code': '645', 'name': ["FRANZ JOSEF LAND, RUSSIA", "FRANZ JOSEF LAND, RUSIA"] },
  '646': { 'code': '646', 'name': ["NORTHERN NORWAY", "REGION NORTE DE NORUEGA"] },
  '647': { 'code': '647', 'name': ["BARENTS SEA", "MAR DE BARENTS"] },
  '648': { 'code': '648', 'name': ["NOVAYA ZEMLYA, RUSSIA", "NOVAYA ZEMLYA, RUSIA"] },
  '649': { 'code': '649', 'name': ["KARA SEA", "MAR KARA"] },
  '650': { 'code': '650', 'name': ["NEAR COAST OF W. SIBERIA, RUSSIA", "CERCA DE LA COSTA OESTE DE SIBERIA, RUSIA"] },
  '651': { 'code': '651', 'name': ["NORTH OF SEVERNAYA ZEMLYA", "NORTE DE SEVERNAYA ZEMLYA"] },
  '652': { 'code': '652', 'name': ["SEVERNAYA ZEMLYA, RUSSIA", "SEVERNAYA ZEMLYA, RUSIA"] },
  '653': { 'code': '653', 'name': ["NEAR COAST OF C. SIBERIA, RUSSIA", "CERCA DE LA COSTA CENTRAL DE SIBERIA, RUSIA"] },
  '654': { 'code': '654', 'name': ["EAST OF SEVERNAYA ZEMLYA, RUSSIA", "ESTE DE SEVERNAYA ZEMLYA, RUSIA"] },
  '655': { 'code': '655', 'name': ["LAPTEV SEA", "MAR LAPTEV"] },
  '656': { 'code': '656', 'name': ["SOUTHEASTERN SIBERIA, RUSSIA", "REGION SUR DE SIBERIA, RUSIA"] },
  '657': { 'code': '657', 'name': ["E. RUSSIA-N.E. CHINA BORDER REG.", "REGION FRONTERIZA ESTE DE RUSIA-N.E. DE CHINA"] },
  '658': { 'code': '658', 'name': ["NORTHEASTERN CHINA", "REGION NORESTE DE CHINA"] },
  '659': { 'code': '659', 'name': ["NORTH KOREA", "KOREA DEL NORTE"] },
  '660': { 'code': '660', 'name': ["SEA OF JAPAN", "MAR DE JAPON"] },
  '661': { 'code': '661', 'name': ["PRIMOR YE, RUSSIA", "PRIMOR YE, RUSSIA"] },
  '662': { 'code': '662', 'name': ["SAKHALIN, RUSSIA", "SAKHALIN, RUSSIA"] },
  '663': { 'code': '663', 'name': ["SEA OF OKHOTSK", "MAR DE OKHOTSK"] },
  '664': { 'code': '664', 'name': ["SOUTHEASTERN CHINA", "REGION SURESTE DE CHINA"] },
  '665': { 'code': '665', 'name': ["YELLOW SEA", "MAR AMARILLO"] },
  '666': { 'code': '666', 'name': ["OFF EASY COAST OF EASTERN CHINA", "FUERA DE LA COSTA ESTE DE LA REGION ESTE DE CHINA"] },
  '667': { 'code': '667', 'name': ["NORTH OF NEW SIBERIAN ISLANDS", "NORTE DE LAS ISLAS DE NUEVA SIBERIA"] },
  '668': { 'code': '668', 'name': ["NEW SIBERIAN ISLANDS, RUSSIA", "ISLAS DE NUEVA SIBERIA, RUSIA"] },
  '669': { 'code': '669', 'name': ["EAST SIBERIAN SEA", "MAR DEL ESTE DE SIBERIA"] },
  '670': { 'code': '670', 'name': ["NEAR N. COAST OF EASTERN SIBERIA", "CERCA DE LA COSTA NORTE DE LA REGION ESTE DE SIBERIA"] },
  '671': { 'code': '671', 'name': ["EASTERN SIBERIA, RUSSIA", "REGION ESTE DE SIBERIA, RUSIA"] },
  '672': { 'code': '672', 'name': ["CHUKCHI SEA", "MAR CHUKCHI"] },
  '673': { 'code': '673', 'name': ["BERING STRAIT", "ESTRECHO DE BERING"] },
  '674': { 'code': '674', 'name': ["ST. LAWRENCE ISLAND, ALASKA REG.", "ISLA DE ST. LAWRENCE, REGION DE ALASKA"] },
  '675': { 'code': '675', 'name': ["BEAUFORT SEA", "MAR BEAUFORT"] },
  '676': { 'code': '676', 'name': ["NORTHERN ALASKA", "REGION NORTE DE ALASKA"] },
  '677': { 'code': '677', 'name': ["NORTHERN YUKON TERRITORY, CANADA", "TERRITOTIO DE LA REGION DEL NORTE DE YUKON, CANADA"] },
  '678': { 'code': '678', 'name': ["QUEEN ELIZABETH ISLANDS, CANADA", "ISLAS QUEEN ELIZABETH, CANADA"] },
  '679': { 'code': '679', 'name': ["NW TERRITORIES - NUNAVUT, CANADA", "TERRITORIOS DEL NOROESTE - NUNAVUT, CANADA"] },
  '680': { 'code': '680', 'name': ["WESTERN GREENLAND", "REGION OESTE DE GROENLANDIA"] },
  '681': { 'code': '681', 'name': ["BAFFIN BAY", "BAHIA DE BAFFIN"] },
  '682': { 'code': '682', 'name': ["BAFFIN ISLAND REGION, CANADA", "REGION DE LA ISLA BAFFIN, CANADA"] },
  '683': { 'code': '683', 'name': ["SOUTHEAST CENTRAL PACIFIC OCEAN", "SURESTE CENTRAL DEL OCEANO PACIFICO"] },
  '684': { 'code': '684', 'name': ["SOUTHERN EAST PACIFIC RISE", "REGION SUR AL ESTE DE LA DORSAL DEL PACIFICO"] },
  '685': { 'code': '685', 'name': ["EASTER ISLAND REGION", "REGION DE LA ISLA DE PASCUA"] },
  '686': { 'code': '686', 'name': ["WEST CHILE RISE", "DORSAL OESTE DE CHILE"] },
  '687': { 'code': '687', 'name': ["JUAN FERNANDEZ ISLANDS REGION", "REGION DE LAS ISLAS JUAN FERNANDEZ"] },
  '688': { 'code': '688', 'name': ["EAST OF NORTH ISLAND, N.Z.", "ESTE DE LA ISLA NORTE, N.Z."] },
  '689': { 'code': '689', 'name': ["CHATHAM ISLANDS, N.Z. REGION", "ISLAS CHATHAM, REGION DE N.Z."] },
  '690': { 'code': '690', 'name': ["SOUTH OF CHATHAM ISLANDS", "SUR DE LAS ISLAS CHATHAM"] },
  '691': { 'code': '691', 'name': ["PACIFIC-ANTARCTIC RIDGE", "DORSAL PACIFICO-ANTARTICA"] },
  '692': { 'code': '692', 'name': ["SOUTHERN PACIFIC OCEAN", "REGION SUR DEL OCEANO PACIFICO"] },
  '693': { 'code': '693', 'name': ["EAST CENTRAL PACIFIC OCEAN", "ESTE CENTRAL DEL OCEANO PACIFICO"] },
  '694': { 'code': '694', 'name': ["CENTRAL EAST PACIFIC RISE", "CENTRO ESTE DE LA DORSAL DEL PACIFICO"] },
  '695': { 'code': '695', 'name': ["WEST OF GALAPAGOS ISLANDS", "OESTE DE LAS ISLAS GALAPAGOS"] },
  '696': { 'code': '696', 'name': ["GALAPAGOS ISLANDS REGION", "REGION DE LAS ISLAS GALAPAGOS"] },
  '697': { 'code': '697', 'name': ["GALAPAGOS ISLANDS, ECUADOR", "ISLAS GALAPAGOS, ECUADOR"] },
  '698': { 'code': '698', 'name': ["SOUTHWEST OF GALAPAGOS ISLANDS", "SUROESTE DE LAS ISLAS GALAPAGOS"] },
  '699': { 'code': '699', 'name': ["SOUTHEAST OF GALAPAGOS ISLANDS", "SURESTE DE LAS ISLAS GALAPAGOS"] },
  '700': { 'code': '700', 'name': ["SOUTH OF TASMANIA", "SUR DE TASMANIA"] },
  '701': { 'code': '701', 'name': ["WEST OF MACQUARIE ISLAND", "OESTE DE LA ISLA MACQUARIE"] },
  '702': { 'code': '702', 'name': ["BALLENY ISLANDS REGION", "REGION DE LAS ISLAS BALLENY"] },
  '703': { 'code': '703', 'name': ["ANDAMAN ISLANDS, INDIA REGION", "ISLAS ANDAMAN, REGION DE INDIA"] },
  '704': { 'code': '704', 'name': ["NICOBAR ISLANDS, INDIA REGION", "ISLAS NICOBAR, REGION DE INDIA"] },
  '705': { 'code': '705', 'name': ["OFF W COAST OF NORTHERN SUMATERA", "FUERA DE LA COSTA OESTE DE LA REGION NORTE DE SUMATRA"] },
  '706': { 'code': '706', 'name': ["NORTHERN SUMATERA, INDONESIA", "REGION NORTE DE SUMATRA, INDONESIA"] },
  '707': { 'code': '707', 'name': ["MALAY PENINSULA", "PENINSULA DE MALAY"] },
  '708': { 'code': '708', 'name': ["GULF OF THAILAND", "GOLFO DE TAILANDIA"] },
  '709': { 'code': '709', 'name': ["SOUTHEASTERN AFGHANISTAN", "REGION SURESTE DE AFGANISTAN"] },
  '710': { 'code': '710', 'name': ["PAKISTAN", "PAKISTAN"] },
  '711': { 'code': '711', 'name': ["SOUTHWESTERN KASHMIR", "REGION SUROESTE DE KASHMIR"] },
  '712': { 'code': '712', 'name': ["INDIA-PAKISTAN BORDER REGION", "REGION FRONTERIZA INDIA-PAKISTAN"] },
  '713': { 'code': '713', 'name': ["CENTRAL KAZAKHSTAN", "CENTRO DE KAZAKHSTAN"] },
  '714': { 'code': '714', 'name': ["SOUTHEASTERN UZBEKISTAN", "REGION SURESTE DE UZBEKISTAN"] },
  '715': { 'code': '715', 'name': ["TAJIKISTAN", "TAJIKISTAN"] },
  '716': { 'code': '716', 'name': ["KYRGYZSTAN", "KYRGYZSTAN"] },
  '717': { 'code': '717', 'name': ["AFGHANISTAN-TAJIKISTAN BORD REG.", "KYRGYZSTAN"] },
  '718': { 'code': '718', 'name': ["HINDU KUSH REGION, AFGHANISTAN", "REGION HINDU KUSH, AFGHANISTAN"] },
  '719': { 'code': '719', 'name': ["TAJIKISTAN-XINJIANG BORDER REG.", "REGION FRONTERIZA TAJIKISTAN-XINJIANG"] },
  '720': { 'code': '720', 'name': ["NORTHWESTERN KASHMIR", "REGION NOROESTE DE KASHMIR"] },
  '721': { 'code': '721', 'name': ["FINLAND", "FINLANDIA"] },
  '722': { 'code': '722', 'name': ["NORWAY-RUSSIA BORDER REGION", "REGION FRONTERIZA NORUEGA-RUSIA"] },
  '723': { 'code': '723', 'name': ["FINLAND-RUSSIA BORDER REGION", "REGION FRONTERIZA FINLANDIA-RUSIA"] },
  '724': { 'code': '724', 'name': ["BALTIC-BELARUS-NW RUSSIA REG.", "REGION NW BALTIC-BELARUS, RUSIA"] },
  '725': { 'code': '725', 'name': ["NORTHWESTERN SIBERIA, RUSSIA", "REGION NOROESTE DE SIBERIA, RUSIA"] },
  '726': { 'code': '726', 'name': ["NORTHCENTRAL SIBERIA, RUSSIA", "REGION NORTECENTRO SIBERIA , RUSIA"] },
  '727': { 'code': '727', 'name': ["VICTORIA LAND, ANTARCTICA", "VICTORIA LAND, ANTARCTICA"] },
  '728': { 'code': '728', 'name': ["ROSS SEA", "MAR DE ROSS"] },
  '729': { 'code': '729', 'name': ["ANTARCTICA", "ANTARCTICA"] },
  '730': { 'code': '730', 'name': ["NORTHERN EAST PACFIC RISE", "REGION NORTE DEL LEVANTAMIENTO ESTE DEL PACIFICO"] },
  '731': { 'code': '731', 'name': ["NORTH OF HONDURAS", "NORTE DE HONDURAS"] },
  '732': { 'code': '732', 'name': ["EAST OF SOUTH SANDWICH ISLANDS", "ESTE DE LAS ISLAS SANDWICH DEL SUR"] },
  '733': { 'code': '733', 'name': ["THAILAND", "TAILANDIA"] },
  '734': { 'code': '734', 'name': ["LAOS", "LAOS"] },
  '735': { 'code': '735', 'name': ["CAMBODIA", "CAMBODIA"] },
  '736': { 'code': '736', 'name': ["VIETNAM", "VIETNAM"] },
  '737': { 'code': '737', 'name': ["GULF OF TONGKING", "GOLFO DE TONGKING"] },
  '738': { 'code': '738', 'name': ["REYKJANES RIDGE", "CORDILLERA REYKJANES"] },
  '739': { 'code': '739', 'name': ["AZORES-CAPE ST. VINCENT RIDGE", "CORDILLERA AZORES-CAPE, SAN VICENTE"] },
  '740': { 'code': '740', 'name': ["OWEN FRACTURE ZONE REGION", "REGION DE FRACTURA DE LA ZONA OWEN"] },
  '741': { 'code': '741', 'name': ["INDIAN OCEAN TRIPLE JUNCTION", "TRIPLE UNION DEL OCEANO INDICO"] },
  '742': { 'code': '742', 'name': ["WESTERN INDIAN-ANTARCTIC RIDGE", "CORDILLERA DE LA REGION OESTE INDIA-ANTARTICA"] },
  '743': { 'code': '743', 'name': ["WESTERN SAHARA", "REGION OESTE DEL SAHARA"] },
  '744': { 'code': '744', 'name': ["MAURITANIA", "MAURITANIA"] },
  '745': { 'code': '745', 'name': ["MALI", "MALI"] },
  '746': { 'code': '746', 'name': ["SENEGAL - GAMBIA REGION", "REGION DE GAMBIA-SENEGAL"] },
  '747': { 'code': '747', 'name': ["GUINEA REGION", "REGION DE GUINEA"] },
  '748': { 'code': '748', 'name': ["SIERRA LEONE", "SIERRA LEON"] },
  '749': { 'code': '749', 'name': ["LIBERIA REGION", "REGION DE LIBERIA"] },
  '750': { 'code': '750', 'name': ["COTE D IVOIRE", "COTE D IVOIRE"] },
  '751': { 'code': '751', 'name': ["BURKINA FASO", "BURKINA FASO"] },
  '752': { 'code': '752', 'name': ["GHANA", "GHANA"] },
  '753': { 'code': '753', 'name': ["BENIN - TOGO REGION", "REGION BENIN-TOGO"] },
  '754': { 'code': '754', 'name': ["NIGER", "NIGER"] },
  '755': { 'code': '755', 'name': ["NIGERIA", "NIGERIA"] },
  '756': { 'code': '756', 'name': ["SOUTHEAST OF EASTER ISLAND", "SURESTE DE LA ISLA DE PASCUA"] },
  '757': { 'code': '757', 'name': ["GALAPAGOS TRIPLE JUNGTION REGION", "REGION DE LA UNION TRIPLE DE GALAPAGOS"] },
  '1': { 'code': '1', 'name': ["CENTRAL REGION OF PUERTO RICO", "REGION CENTRAL DE PUERTO RICO"] },
  '2': { 'code': '2', 'name': ["SOUTH REGION OF PUERTO RICO", "REGION SUR DE PUERTO RICO"] },
  '3': { 'code': '3', 'name': ["SOUTHEAST REGION OF PUERTO RICO", "REGION SUR-ESTE DE PUERTO RICO"] },
  '4': { 'code': '4', 'name': ["EAST REGION OF PUERTO RICO", "REGION ESTE DE PUERTO RICO"] },
  '5': { 'code': '5', 'name': ["NORTHEAST REGION OF PUERTO RICO", "REGION NOR-ESTE DE PUERTO RICO"] },
  '6': { 'code': '6', 'name': ["NORTH REGION OF PUERTO RICO", "REGION NORTE DE PUERTO RICO"] },
  '7': { 'code': '7', 'name': ["NORTHWEST REGION OF PUERTO RICO", "REGION NOR-OESTE DE PUERTO RICO"] },
  '8': { 'code': '8', 'name': ["WEST REGION OF PUERTO RICO", "REGION OESTE DE PUERTO RICO"] },
  '9': { 'code': '9', 'name': ["SOUTHWEST REGION OF PUERTO RICO", "REGION SUR-OESTE DE PUERTO RICO"] },
  '10': { 'code': '10', 'name': ["SOUTHERN PUERTO RICO", "ZONA AL SUR DE PUERTO RICO"] },
  '11': { 'code': '11', 'name': ["WESTERN PUERTO RICO", "ZONA AL OESTE DE PUERTO RICO"] },
  '12': { 'code': '12', 'name': ["NORTHERN PUERTO RICO", "ZONA AL NORTE DE PUERTO RICO"] },
  '13': { 'code': '13', 'name': ["EASTERN PUERTO RICO", "ZONA AL ESTE DE PUERTO RICO"] },
  '14': { 'code': '14', 'name': ["PUERTO RICO TRENCH", "TRINCHERA DE PUERTO RICO"] },
  '15': { 'code': '15', 'name': ["MUERTOS TROUGH", "TRINCHERA DE MUERTOS"] },
  '16': { 'code': '16', 'name': ["LEEWARD ISLANDS", "ISLAS DE BARLOVENTO"] },
  '17': { 'code': '17', 'name': ["SAINT CROIX PLATFORM", "PLATAFORMA DE SANTA CRUZ"] },
  '18': { 'code': '18', 'name': ["SAINT CROIX RIDGE", "LOMO DE SANTA CRUZ"] },
  '19': { 'code': '19', 'name': ["EASTERN DOMINICAN REPUBLIC", "ZONA ORIENTAL DE LA REPUBLICA DOMINICANA"] },
  '20': { 'code': '20', 'name': ["SEPTENTRIONAL FAULT ZONE", "ZONA DE LA FALLA SEPTENTRIONAL"] },
  '21': { 'code': '21', 'name': ["MONA PASSAGE", "PASAJE DE LA MONA"] },
  '22': { 'code': '22', 'name': ["MONA CANYON", "CANYON DE LA MONA"] },
  '23': { 'code': '23', 'name': ["19&deg; N FAULT ZONE", "ZONA DE FALLA DE LOS 19&deg; N"] },
  '24': { 'code': '24', 'name': ["SOMBRERO SEISMIC ZONE", "ZONA SISMICA DEL SOMBRERO"] },
  '25': { 'code': '25', 'name': ["VIRGIN ISLANDS PLATFORM", "PLATAFORMA DE LAS ISLAS VIRGENES"] },
  '26': { 'code': '26', 'name': ["SAINT CROIX", "SANTA CRUZ"] },
  '27': { 'code': '27', 'name': ["VIRGIN ISLANDS BASIN", "DEPRESION DE LAS ISLAS VIRGENES"] },
  '28': { 'code': '28', 'name': ["ANEGADA PASSAGE", "PASAJE DE ANEGADA"] },
};
